#
# Copyright 2009 Nexell Co.
#
# Makefile for the NXP4330

obj-y					:= board.o device.o
obj-$(CONFIG_SUSPEND)			+= pm.o
obj-$(CONFIG_ION_NXP)			+= dev-ion.o
obj-$(CONFIG_USB_CONNECT_NXP_DRV)	+= usb-connector.o
obj-$(CONFIG_ESP8089)			+= wifi_pm_esp8089.o
