#ifndef __CFG_GPIO_R3K_H__
#define __CFG_GPIO_R3K_H__

#include <mach/nxp4330.h>
/*------------------------------------------------------------------------------
*	GPIO Bank A
*/
#define PAD_GPIOA00_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VOUT_PCLK_R */
#define PAD_GPIOA01_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD0 */
#define PAD_GPIOA02_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD1 */
#define PAD_GPIOA03_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD2 */
#define PAD_GPIOA04_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD3 */
#define PAD_GPIOA05_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD4 */
#define PAD_GPIOA06_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD5 */
#define PAD_GPIOA07_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD6 */

#define PAD_GPIOA08_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD7 */
#define PAD_GPIOA09_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD8 */
#define PAD_GPIOA10_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD9 */
#define PAD_GPIOA11_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD10 */
#define PAD_GPIOA12_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD11 */
#define PAD_GPIOA13_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD12 */
#define PAD_GPIOA14_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD13 */
#define PAD_GPIOA15_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD14 */

#define PAD_GPIOA16_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD15 */
#define PAD_GPIOA17_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD16 */
#define PAD_GPIOA18_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD17 */
#define PAD_GPIOA19_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD18 */
#define PAD_GPIOA20_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD19 */
#define PAD_GPIOA21_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD20 */
#define PAD_GPIOA22_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD21 */
#define PAD_GPIOA23_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD22 */

#define PAD_GPIOA24_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD23 */
#define PAD_GPIOA25_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VOUT_PVSYNC_R */
#define PAD_GPIOA26_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VOUT_PHSYNC_R */
#define PAD_GPIOA27_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VOUT_DE_R */
#define PAD_GPIOA28_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_PCLK */
#define PAD_GPIOA29_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCLK0_R */
#define PAD_GPIOA30_R3K		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDEX0 */
#define PAD_GPIOA31_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCMD0_R */
/*------------------------------------------------------------------------------
*	GPIO Bank B
*/
#define PAD_GPIOB00_R3K		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDEX1 */
#define PAD_GPIOB01_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT00_R */
#define PAD_GPIOB02_R3K		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDEX2 */
#define PAD_GPIOB03_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT01_R */
#define PAD_GPIOB04_R3K		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDEX3 */
#define PAD_GPIOB05_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT02_R */
#define PAD_GPIOB06_R3K		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDEX4 */
#define PAD_GPIOB07_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT03_R */

#define PAD_GPIOB08_R3K		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDEX5 */
#define PAD_GPIOB09_R3K		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDEX6 */
#define PAD_GPIOB10_R3K		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDEX7 */
#define PAD_GPIOB11_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NAND_CLE_R */
#define PAD_GPIOB12_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NAND_ALE_R */
#define PAD_GPIOB13_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD0 */
#define PAD_GPIOB14_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_UP | PAD_STRENGTH_2)		/* Pin Use: NAND_RNB */
#define PAD_GPIOB15_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD1 */

#define PAD_GPIOB16_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NAND_NFOE_R_L */
#define PAD_GPIOB17_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD2 */
#define PAD_GPIOB18_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NAND_NFWE_R_L */
#define PAD_GPIOB19_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD3 */
#define PAD_GPIOB20_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD4 */
#define PAD_GPIOB21_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD5 */
#define PAD_GPIOB22_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD6 */
#define PAD_GPIOB23_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD7 */

#define PAD_GPIOB24_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: HOME_BTN_L */
#define PAD_GPIOB25_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DPAD_UP_L */
#define PAD_GPIOB26_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DPAD_DN_L */
#define PAD_GPIOB27_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DPAD_RIGHT_L */
#define PAD_GPIOB28_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DPAD_LEFT_L */
#define PAD_GPIOB29_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VOL_UP_L */
#define PAD_GPIOB30_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VOL_DOWN_L */
#define PAD_GPIOB31_R3K		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: HP_DETECT */
/*------------------------------------------------------------------------------
*	GPIO Bank C
*/
#define PAD_GPIOC00_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: WIFI_RST_L */
#define PAD_GPIOC01_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC02_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC03_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: MCU_HDMI_CEC */
#define PAD_GPIOC04_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PMIC_FLT_L */
#define PAD_GPIOC05_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_UP | PAD_STRENGTH_2)		/* Pin Use: CIP_L */
#define PAD_GPIOC06_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: ACCEL_INT */
#define PAD_GPIOC07_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CPT_WAKE */

#define PAD_GPIOC08_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CPT_INT */
#define PAD_GPIOC09_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPCLK2 */
#define PAD_GPIOC10_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPFRM2 */
#define PAD_GPIOC11_R3K		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPRXD2 */
#define PAD_GPIOC12_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPTXD2 */
#define PAD_GPIOC13_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC14_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT3 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID2_PCLK */
#define PAD_GPIOC15_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID2_ENA_L */

#define PAD_GPIOC16_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID2_RESET_L */
#define PAD_GPIOC17_R3K		(PAD_MODE_IN | PAD_FUNC_ALT3 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID2_0 */
#define PAD_GPIOC18_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID2_1 */
#define PAD_GPIOC19_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID2_2 */
#define PAD_GPIOC20_R3K		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID2_3 */
#define PAD_GPIOC21_R3K		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID2_4 */
#define PAD_GPIOC22_R3K		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID2_5 */
#define PAD_GPIOC23_R3K		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID2_6 */

#define PAD_GPIOC24_R3K		(PAD_MODE_IN | PAD_FUNC_ALT3 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID2_7 */
#define PAD_GPIOC25_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: TBD */
#define PAD_GPIOC26_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC27_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC28_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: MCU_nSCS1 */
#define PAD_GPIOC29_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPCLK0_R */
#define PAD_GPIOC30_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPFRM0 */
#define PAD_GPIOC31_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPTXD0 */
/*------------------------------------------------------------------------------
*	GPIO Bank D
*/
#define PAD_GPIOD00_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPRXD0 */
#define PAD_GPIOD01_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: MCU_PWM0 */
#define PAD_GPIOD02_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SCL0 */
#define PAD_GPIOD03_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDA0 */
#define PAD_GPIOD04_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SCL1 */
#define PAD_GPIOD05_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDA1 */
#define PAD_GPIOD06_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SCL2 */
#define PAD_GPIOD07_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDA2 */

#define PAD_GPIOD08_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOD09_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SDOUT_OUT */
#define PAD_GPIOD10_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SSYNC_OUT */
#define PAD_GPIOD11_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SDIN */
#define PAD_GPIOD12_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SMCLK_OUT */
#define PAD_GPIOD13_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SBCLK_OUT */
#define PAD_GPIOD14_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: RX0 */
#define PAD_GPIOD15_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: ETHER_INT */

#define PAD_GPIOD16_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CHG_CE_L */
#define PAD_GPIOD17_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CHG_INT */
#define PAD_GPIOD18_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: TX0 */
#define PAD_GPIOD19_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: A100_INT */
#define PAD_GPIOD20_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: LCD_LED_ENA */
#define PAD_GPIOD21_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: USB_PWR_OK_L */
#define PAD_GPIOD22_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCLK1_R */
#define PAD_GPIOD23_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCMD1_R */

#define PAD_GPIOD24_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT10_R */
#define PAD_GPIOD25_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT11_R */
#define PAD_GPIOD26_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT12_R */
#define PAD_GPIOD27_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT13_R */
#define PAD_GPIOD28_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_0 */
#define PAD_GPIOD29_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_1 */
#define PAD_GPIOD30_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_2 */
#define PAD_GPIOD31_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_3 */
/*------------------------------------------------------------------------------
*	GPIO Bank E
*/
#define PAD_GPIOE00_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_4 */
#define PAD_GPIOE01_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_5 */
#define PAD_GPIOE02_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_6 */
#define PAD_GPIOE03_R3K		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_7 */
#define PAD_GPIOE04_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_PCLK */
#define PAD_GPIOE05_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_HSYNC */
#define PAD_GPIOE06_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_VSYNC */
#define PAD_GPIOE07_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_RESET_L */

#define PAD_GPIOE08_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOE09_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: MCU_SA2 */
#define PAD_GPIOE10_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOE11_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOE12_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOE13_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_ENA_L */
#define PAD_GPIOE14_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SCK_R */
#define PAD_GPIOE15_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: LCD_SCS_L */

#define PAD_GPIOE16_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOE17_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOE18_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE19_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDI */
#define PAD_GPIOE20_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOE21_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOE22_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOE23_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */

#define PAD_GPIOE24_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CHG_FLT */
#define PAD_GPIOE25_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TRST_L */
#define PAD_GPIOE26_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TMS */
#define PAD_GPIOE27_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TDI */
#define PAD_GPIOE28_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TCK */
#define PAD_GPIOE29_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TDO */
#define PAD_GPIOE30_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: MCU_nSOE */
#define PAD_GPIOE31_R3K		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: MCU_nSWE */
/*------------------------------------------------------------------------------
*	GPIO Bank ALV
*/
#define PAD_GPIOALV00_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOALV01_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOALV02_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOALV03_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOALV04_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOALV05_R3K		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */

/*------------------------------------------------------------------------------
*	BUS Signal
*/
#define	PAD_BUS_STATIC_CNTL_R3K	(NX_CLKPWR_BUSPAD_STATIC_CNTL | PAD_STRENGTH_2)
#define	PAD_BUS_STATIC_ADDR_R3K	(NX_CLKPWR_BUSPAD_STATIC_ADDR | PAD_STRENGTH_2)
#define	PAD_BUS_STATIC_DATA_R3K	(NX_CLKPWR_BUSPAD_STATIC_DATA | PAD_STRENGTH_2)
#define	PAD_BUS_HSYNC_R3K	(NX_CLKPWR_BUSPAD_HSYNC | PAD_STRENGTH_2)
#define	PAD_BUS_VSYNC_R3K	(NX_CLKPWR_BUSPAD_VSYNC | PAD_STRENGTH_2)
#define	PAD_BUS_DE_R3K	(NX_CLKPWR_BUSPAD_DE | PAD_STRENGTH_2)

extern const U32 io_pad_r3k[NUMBER_OF_GPIO_MODULE][32];

#ifndef ALVPADS
#define ALVPADS 6
#endif
extern const U32 alv_pad_r3k[ALVPADS];

extern const U32 bus_pad_r3k[6];
#endif /* __CFG_GPIO_R3K_H__ */
