#ifndef __CFG_GPIO_GLASGOW_BETA_H__
#define __CFG_GPIO_GLASGOW_BETA_H__

#include <mach/nxp4330.h>
/*------------------------------------------------------------------------------
*	GPIO Bank A
*/
#define PAD_GPIOA00_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOA01_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DISD0 */
#define PAD_GPIOA02_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DISD1 */
#define PAD_GPIOA03_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DISD2 */
#define PAD_GPIOA04_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DISD3 */
#define PAD_GPIOA05_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DISD4 */
#define PAD_GPIOA06_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DISD5 */
#define PAD_GPIOA07_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DISD6 */

#define PAD_GPIOA08_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DISD7 */
#define PAD_GPIOA09_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOA10_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOA11_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOA12_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOA13_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: USBOTG_ID */
#define PAD_GPIOA14_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: USBOTG_FLT_L */
#define PAD_GPIOA15_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: USB_MUX_SEL_R */

#define PAD_GPIOA16_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOA17_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOA18_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOA19_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOA20_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOA21_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOA22_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOA23_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */

#define PAD_GPIOA24_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOA25_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOA26_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOA27_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOA28_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOA29_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCLK0_R */
#define PAD_GPIOA30_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDEX0 */
#define PAD_GPIOA31_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCMD0_R */
/*------------------------------------------------------------------------------
*	GPIO Bank B
*/
#define PAD_GPIOB00_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDEX1 */
#define PAD_GPIOB01_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT00_R */
#define PAD_GPIOB02_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDEX2 */
#define PAD_GPIOB03_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT01_R */
#define PAD_GPIOB04_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDEX3 */
#define PAD_GPIOB05_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT02_R */
#define PAD_GPIOB06_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDEX4 */
#define PAD_GPIOB07_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT03_R */

#define PAD_GPIOB08_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDEX5 */
#define PAD_GPIOB09_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDEX6 */
#define PAD_GPIOB10_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDEX7 */
#define PAD_GPIOB11_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOB12_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOB13_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD0 */
#define PAD_GPIOB14_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOB15_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD1 */

#define PAD_GPIOB16_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOB17_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD2 */
#define PAD_GPIOB18_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOB19_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD3 */
#define PAD_GPIOB20_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD4 */
#define PAD_GPIOB21_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD5 */
#define PAD_GPIOB22_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD6 */
#define PAD_GPIOB23_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD7 */

#define PAD_GPIOB24_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOB25_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOB26_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOB27_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SYNC_BUTTON_L */
#define PAD_GPIOB28_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOB29_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOB30_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOB31_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
/*------------------------------------------------------------------------------
*	GPIO Bank C
*/
#define PAD_GPIOC00_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC01_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC02_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC03_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: MCU_HDMI_CEC */
#define PAD_GPIOC04_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC05_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CTS1 */
#define PAD_GPIOC06_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: RTS1 */
#define PAD_GPIOC07_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */

#define PAD_GPIOC08_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CART_CD */
#define PAD_GPIOC09_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC10_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC11_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT3 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: USB_DRV_VBUS */
#define PAD_GPIOC12_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC13_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC14_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_HIGH | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: WIFI_RST_L */
#define PAD_GPIOC15_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: BT_RESET_L */

#define PAD_GPIOC16_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: WIFI_HOST_WAKE */
#define PAD_GPIOC17_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC18_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCLK2_R */
#define PAD_GPIOC19_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCMD2_R */
#define PAD_GPIOC20_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT20_R */
#define PAD_GPIOC21_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT21_R */
#define PAD_GPIOC22_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT22_R */
#define PAD_GPIOC23_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT23_R */

#define PAD_GPIOC24_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: BT_LINK */
#define PAD_GPIOC25_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: nSWAIT */
#define PAD_GPIOC26_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC27_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC28_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC29_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPCLK0 */
#define PAD_GPIOC30_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPFRM0 */
#define PAD_GPIOC31_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPTXD0 */
/*------------------------------------------------------------------------------
*	GPIO Bank D
*/
#define PAD_GPIOD00_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPRXD0 */
#define PAD_GPIOD01_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_HIGH | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: LED1_R */
#define PAD_GPIOD02_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SCL0 */
#define PAD_GPIOD03_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDA0 */
#define PAD_GPIOD04_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOD05_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOD06_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOD07_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */

#define PAD_GPIOD08_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOD09_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SDOUT0 */
#define PAD_GPIOD10_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SBCLK0 */
#define PAD_GPIOD11_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SDIN0 */
#define PAD_GPIOD12_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SLRCK0 */
#define PAD_GPIOD13_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SMCLK0 */
#define PAD_GPIOD14_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_UP | PAD_STRENGTH_2)		/* Pin Use: RX0 */
#define PAD_GPIOD15_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: RX1 */

#define PAD_GPIOD16_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOD17_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOD18_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: TX0 */
#define PAD_GPIOD19_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: TX1 */
#define PAD_GPIOD20_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOD21_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOD22_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCLK1_R */
#define PAD_GPIOD23_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCMD1_R */

#define PAD_GPIOD24_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT10_R */
#define PAD_GPIOD25_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT11_R */
#define PAD_GPIOD26_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT12_R */
#define PAD_GPIOD27_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT13_R */
#define PAD_GPIOD28_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOD29_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOD30_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOD31_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
/*------------------------------------------------------------------------------
*	GPIO Bank E
*/
#define PAD_GPIOE00_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE01_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE02_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE03_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE04_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE05_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE06_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE07_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */

#define PAD_GPIOE08_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE09_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE10_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE11_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE12_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE13_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE14_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE15_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */

#define PAD_GPIOE16_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE17_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE18_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE19_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE20_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE21_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE22_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE23_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */

#define PAD_GPIOE24_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: MCU_GTXCLK */
#define PAD_GPIOE25_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TRST_L */
#define PAD_GPIOE26_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TMS */
#define PAD_GPIOE27_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TDI */
#define PAD_GPIOE28_GLASGOW_BETA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TCK */
#define PAD_GPIOE29_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TDO */
#define PAD_GPIOE30_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE31_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
/*------------------------------------------------------------------------------
*	GPIO Bank ALV
*/
#define PAD_GPIOALV00_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOALV01_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOALV02_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOALV03_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOALV04_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOALV05_GLASGOW_BETA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */

/*------------------------------------------------------------------------------
*	BUS Signal
*/
#define	PAD_BUS_STATIC_CNTL_GLASGOW_BETA	(NX_CLKPWR_BUSPAD_STATIC_CNTL | PAD_STRENGTH_2)
#define	PAD_BUS_STATIC_ADDR_GLASGOW_BETA	(NX_CLKPWR_BUSPAD_STATIC_ADDR | PAD_STRENGTH_2)
#define	PAD_BUS_STATIC_DATA_GLASGOW_BETA	(NX_CLKPWR_BUSPAD_STATIC_DATA | PAD_STRENGTH_2)
#define	PAD_BUS_HSYNC_GLASGOW_BETA	(NX_CLKPWR_BUSPAD_HSYNC | PAD_STRENGTH_2)
#define	PAD_BUS_VSYNC_GLASGOW_BETA	(NX_CLKPWR_BUSPAD_VSYNC | PAD_STRENGTH_2)
#define	PAD_BUS_DE_GLASGOW_BETA	(NX_CLKPWR_BUSPAD_DE | PAD_STRENGTH_2)

extern const U32 io_pad_glasgow_beta[NUMBER_OF_GPIO_MODULE][32];

#ifndef ALVPADS
#define ALVPADS 6
#endif
extern const U32 alv_pad_glasgow_beta[ALVPADS];

extern const U32 bus_pad_glasgow_beta[6];
#endif /* __CFG_GPIO_GLASGOW_BETA_H__ */
