#ifndef __CFG_GPIO_XANADU_ALPHA_H__
#define __CFG_GPIO_XANADU_ALPHA_H__

#include <mach/nxp4330.h>
/*------------------------------------------------------------------------------
*	GPIO Bank A
*/
#define PAD_GPIOA00_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VOUT_PCLK_R */
#define PAD_GPIOA01_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD0 */
#define PAD_GPIOA02_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD1 */
#define PAD_GPIOA03_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD2 */
#define PAD_GPIOA04_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD3 */
#define PAD_GPIOA05_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD4 */
#define PAD_GPIOA06_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD5 */
#define PAD_GPIOA07_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD6 */

#define PAD_GPIOA08_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD7 */
#define PAD_GPIOA09_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD8 */
#define PAD_GPIOA10_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD9 */
#define PAD_GPIOA11_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD10 */
#define PAD_GPIOA12_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD11 */
#define PAD_GPIOA13_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD12 */
#define PAD_GPIOA14_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD13 */
#define PAD_GPIOA15_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD14 */

#define PAD_GPIOA16_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD15 */
#define PAD_GPIOA17_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD16 */
#define PAD_GPIOA18_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD17 */
#define PAD_GPIOA19_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD18 */
#define PAD_GPIOA20_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD19 */
#define PAD_GPIOA21_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD20 */
#define PAD_GPIOA22_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD21 */
#define PAD_GPIOA23_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD22 */

#define PAD_GPIOA24_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD23 */
#define PAD_GPIOA25_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VOUT_PVSYNC_R */
#define PAD_GPIOA26_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VOUT_PHSYNC_R */
#define PAD_GPIOA27_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VOUT_DE_R */
#define PAD_GPIOA28_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_PCLK */
#define PAD_GPIOA29_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCLK0_R */
#define PAD_GPIOA30_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_0 */
#define PAD_GPIOA31_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCMD0_R */
/*------------------------------------------------------------------------------
*	GPIO Bank B
*/
#define PAD_GPIOB00_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_1 */
#define PAD_GPIOB01_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT00_R */
#define PAD_GPIOB02_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_2 */
#define PAD_GPIOB03_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT01_R */
#define PAD_GPIOB04_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_3 */
#define PAD_GPIOB05_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT02_R */
#define PAD_GPIOB06_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_4 */
#define PAD_GPIOB07_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT03_R */

#define PAD_GPIOB08_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_5 */
#define PAD_GPIOB09_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_6 */
#define PAD_GPIOB10_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_7 */
#define PAD_GPIOB11_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NAND_CLE_R */
#define PAD_GPIOB12_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NAND_ALE_R */
#define PAD_GPIOB13_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD0 */
#define PAD_GPIOB14_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NAND_RNB */
#define PAD_GPIOB15_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD1 */

#define PAD_GPIOB16_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NAND_NFOE_R_L */
#define PAD_GPIOB17_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD2 */
#define PAD_GPIOB18_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NAND_NFWE_R_L */
#define PAD_GPIOB19_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD3 */
#define PAD_GPIOB20_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD4 */
#define PAD_GPIOB21_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD5 */
#define PAD_GPIOB22_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD6 */
#define PAD_GPIOB23_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD7 */

#define PAD_GPIOB24_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CTP_RST_RTP_Y2_R */
#define PAD_GPIOB25_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CTP_INT_RTP_X2_R */
#define PAD_GPIOB26_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOB27_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOB28_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOB29_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VOL_UP_L */
#define PAD_GPIOB30_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VOL_DOWN_L */
#define PAD_GPIOB31_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
/*------------------------------------------------------------------------------
*	GPIO Bank C
*/
#define PAD_GPIOC00_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC01_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC02_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC03_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC04_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PMIC_INT_L */
#define PAD_GPIOC05_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CIP_L */
#define PAD_GPIOC06_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: ACCEL_INT */
#define PAD_GPIOC07_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */

#define PAD_GPIOC08_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC09_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPCLK2 */
#define PAD_GPIOC10_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPFRM2 */
#define PAD_GPIOC11_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPRXD2 */
#define PAD_GPIOC12_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPTXD2 */
#define PAD_GPIOC13_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC14_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC15_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID2_ENA_L */

#define PAD_GPIOC16_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID2_RESET_L */
#define PAD_GPIOC17_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC18_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCLK2 */
#define PAD_GPIOC19_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCMD2 */
#define PAD_GPIOC20_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT20 */
#define PAD_GPIOC21_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT21 */
#define PAD_GPIOC22_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT22 */
#define PAD_GPIOC23_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT23 */

#define PAD_GPIOC24_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC25_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: nSWAIT */
#define PAD_GPIOC26_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC27_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC28_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC29_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPCLK0_R */
#define PAD_GPIOC30_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPFRM0 */
#define PAD_GPIOC31_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPTXD0 */
/*------------------------------------------------------------------------------
*	GPIO Bank D
*/
#define PAD_GPIOD00_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPRXD0 */
#define PAD_GPIOD01_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: MCU_PWM0 */
#define PAD_GPIOD02_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SCL0 */
#define PAD_GPIOD03_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDA0 */
#define PAD_GPIOD04_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SCL1 */
#define PAD_GPIOD05_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDA1 */
#define PAD_GPIOD06_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CTP_SCL_RTP_Y1_R */
#define PAD_GPIOD07_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CTP_SCL_RTP_X1_R */

#define PAD_GPIOD08_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOD09_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SDOUT */
#define PAD_GPIOD10_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SBCLK */
#define PAD_GPIOD11_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SDIN */
#define PAD_GPIOD12_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SSYNC */
#define PAD_GPIOD13_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SMCLK */
#define PAD_GPIOD14_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: RX0 */
#define PAD_GPIOD15_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */

#define PAD_GPIOD16_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOD17_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOD18_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: TX0 */
#define PAD_GPIOD19_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_HIGH | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: WIFI_RST_L */
#define PAD_GPIOD20_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CHG_FLT */
#define PAD_GPIOD21_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOD22_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCLK1_R */
#define PAD_GPIOD23_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCMD1_R */

#define PAD_GPIOD24_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT10_R */
#define PAD_GPIOD25_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT11_R */
#define PAD_GPIOD26_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT12_R */
#define PAD_GPIOD27_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT13_R */
#define PAD_GPIOD28_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_0 */
#define PAD_GPIOD29_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_1 */
#define PAD_GPIOD30_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_2 */
#define PAD_GPIOD31_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_3 */
/*------------------------------------------------------------------------------
*	GPIO Bank E
*/
#define PAD_GPIOE00_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_4 */
#define PAD_GPIOE01_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_5 */
#define PAD_GPIOE02_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_6 */
#define PAD_GPIOE03_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_7 */
#define PAD_GPIOE04_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_PCLK */
#define PAD_GPIOE05_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_ENAL */
#define PAD_GPIOE06_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_RESET_L */
#define PAD_GPIOE07_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */

#define PAD_GPIOE08_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOE09_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DPAD_LEFT_L */
#define PAD_GPIOE10_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: HP_DETECT */
#define PAD_GPIOE11_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOE12_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: AUDIO_INT */
#define PAD_GPIOE13_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: USB2_OTG_ID */
#define PAD_GPIOE14_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SCK */
#define PAD_GPIOE15_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: LCD_SCS_L */

#define PAD_GPIOE16_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: AUDIO_MUTE */
#define PAD_GPIOE17_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_HIGH | PAD_PULL_UP | PAD_STRENGTH_2)		/* Pin Use: AUDIO_RST_L */
#define PAD_GPIOE18_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOE19_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDI */
#define PAD_GPIOE20_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: HOME_BTN_L */
#define PAD_GPIOE21_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DPAD_DN_L */
#if 1	/*  Experiment; output high, so backlight will be on */
#define PAD_GPIOE22_XANADU_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_HIGH | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: LCD_LED_ENA */
#else
#define PAD_GPIOE22_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: LCD_LED_ENA */
#endif	/* 7feb14 */
#define PAD_GPIOE23_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DPAD_RIGHT_L */

#define PAD_GPIOE24_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DPAD_UP_L */
#define PAD_GPIOE25_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TRST_L */
#define PAD_GPIOE26_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TMS */
#define PAD_GPIOE27_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TDI */
#define PAD_GPIOE28_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TCK */
#define PAD_GPIOE29_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TDO */
#define PAD_GPIOE30_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: USB_OTG_ID */
#define PAD_GPIOE31_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: USB_PWR_OK_L */
/*------------------------------------------------------------------------------
*	GPIO Bank ALV
*/
#define PAD_GPIOALV00_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOALV01_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOALV02_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOALV03_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOALV04_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOALV05_XANADU_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */

/*------------------------------------------------------------------------------
*	BUS Signal
*/
#define	PAD_BUS_STATIC_CNTL_XANADU_ALPHA	(NX_CLKPWR_BUSPAD_STATIC_CNTL | PAD_STRENGTH_2)
#define	PAD_BUS_STATIC_ADDR_XANADU_ALPHA	(NX_CLKPWR_BUSPAD_STATIC_ADDR | PAD_STRENGTH_2)
#define	PAD_BUS_STATIC_DATA_XANADU_ALPHA	(NX_CLKPWR_BUSPAD_STATIC_DATA | PAD_STRENGTH_2)
#define	PAD_BUS_HSYNC_XANADU_ALPHA	(NX_CLKPWR_BUSPAD_HSYNC | PAD_STRENGTH_2)
#define	PAD_BUS_VSYNC_XANADU_ALPHA	(NX_CLKPWR_BUSPAD_VSYNC | PAD_STRENGTH_2)
#define	PAD_BUS_DE_XANADU_ALPHA	(NX_CLKPWR_BUSPAD_DE | PAD_STRENGTH_2)

extern const U32 io_pad_xanadu_alpha[NUMBER_OF_GPIO_MODULE][32];

extern const U32 alv_pad_xanadu_alpha[8];

extern const U32 bus_pad_xanadu_alpha[6];
#endif /* __CFG_GPIO_XANADU_ALPHA_H__ */
