
#include <cfg_type.h>
#include <../../xanadu/include/cfg_gpio_xanadu_alpha.h>

const U32 io_pad_xanadu_alpha[NUMBER_OF_GPIO_MODULE][32] = {
	/* GPIO group A */
	{
	PAD_GPIOA00_XANADU_ALPHA, PAD_GPIOA01_XANADU_ALPHA, PAD_GPIOA02_XANADU_ALPHA, PAD_GPIOA03_XANADU_ALPHA,
	PAD_GPIOA04_XANADU_ALPHA, PAD_GPIOA05_XANADU_ALPHA, PAD_GPIOA06_XANADU_ALPHA, PAD_GPIOA07_XANADU_ALPHA,
	PAD_GPIOA08_XANADU_ALPHA, PAD_GPIOA09_XANADU_ALPHA, PAD_GPIOA10_XANADU_ALPHA, PAD_GPIOA11_XANADU_ALPHA,
	PAD_GPIOA12_XANADU_ALPHA, PAD_GPIOA13_XANADU_ALPHA, PAD_GPIOA14_XANADU_ALPHA, PAD_GPIOA15_XANADU_ALPHA,
	PAD_GPIOA16_XANADU_ALPHA, PAD_GPIOA17_XANADU_ALPHA, PAD_GPIOA18_XANADU_ALPHA, PAD_GPIOA19_XANADU_ALPHA,
	PAD_GPIOA20_XANADU_ALPHA, PAD_GPIOA21_XANADU_ALPHA, PAD_GPIOA22_XANADU_ALPHA, PAD_GPIOA23_XANADU_ALPHA,
	PAD_GPIOA24_XANADU_ALPHA, PAD_GPIOA25_XANADU_ALPHA, PAD_GPIOA26_XANADU_ALPHA, PAD_GPIOA27_XANADU_ALPHA,
	PAD_GPIOA28_XANADU_ALPHA, PAD_GPIOA29_XANADU_ALPHA, PAD_GPIOA30_XANADU_ALPHA, PAD_GPIOA31_XANADU_ALPHA,
	},
	/* GPIO group B */
	{
	PAD_GPIOB00_XANADU_ALPHA, PAD_GPIOB01_XANADU_ALPHA, PAD_GPIOB02_XANADU_ALPHA, PAD_GPIOB03_XANADU_ALPHA,
	PAD_GPIOB04_XANADU_ALPHA, PAD_GPIOB05_XANADU_ALPHA, PAD_GPIOB06_XANADU_ALPHA, PAD_GPIOB07_XANADU_ALPHA,
	PAD_GPIOB08_XANADU_ALPHA, PAD_GPIOB09_XANADU_ALPHA, PAD_GPIOB10_XANADU_ALPHA, PAD_GPIOB11_XANADU_ALPHA,
	PAD_GPIOB12_XANADU_ALPHA, PAD_GPIOB13_XANADU_ALPHA, PAD_GPIOB14_XANADU_ALPHA, PAD_GPIOB15_XANADU_ALPHA,
	PAD_GPIOB16_XANADU_ALPHA, PAD_GPIOB17_XANADU_ALPHA, PAD_GPIOB18_XANADU_ALPHA, PAD_GPIOB19_XANADU_ALPHA,
	PAD_GPIOB20_XANADU_ALPHA, PAD_GPIOB21_XANADU_ALPHA, PAD_GPIOB22_XANADU_ALPHA, PAD_GPIOB23_XANADU_ALPHA,
	PAD_GPIOB24_XANADU_ALPHA, PAD_GPIOB25_XANADU_ALPHA, PAD_GPIOB26_XANADU_ALPHA, PAD_GPIOB27_XANADU_ALPHA,
	PAD_GPIOB28_XANADU_ALPHA, PAD_GPIOB29_XANADU_ALPHA, PAD_GPIOB30_XANADU_ALPHA, PAD_GPIOB31_XANADU_ALPHA,
	},
	/* GPIO group C */
	{
	PAD_GPIOC00_XANADU_ALPHA, PAD_GPIOC01_XANADU_ALPHA, PAD_GPIOC02_XANADU_ALPHA, PAD_GPIOC03_XANADU_ALPHA,
	PAD_GPIOC04_XANADU_ALPHA, PAD_GPIOC05_XANADU_ALPHA, PAD_GPIOC06_XANADU_ALPHA, PAD_GPIOC07_XANADU_ALPHA,
	PAD_GPIOC08_XANADU_ALPHA, PAD_GPIOC09_XANADU_ALPHA, PAD_GPIOC10_XANADU_ALPHA, PAD_GPIOC11_XANADU_ALPHA,
	PAD_GPIOC12_XANADU_ALPHA, PAD_GPIOC13_XANADU_ALPHA, PAD_GPIOC14_XANADU_ALPHA, PAD_GPIOC15_XANADU_ALPHA,
	PAD_GPIOC16_XANADU_ALPHA, PAD_GPIOC17_XANADU_ALPHA, PAD_GPIOC18_XANADU_ALPHA, PAD_GPIOC19_XANADU_ALPHA,
	PAD_GPIOC20_XANADU_ALPHA, PAD_GPIOC21_XANADU_ALPHA, PAD_GPIOC22_XANADU_ALPHA, PAD_GPIOC23_XANADU_ALPHA,
	PAD_GPIOC24_XANADU_ALPHA, PAD_GPIOC25_XANADU_ALPHA, PAD_GPIOC26_XANADU_ALPHA, PAD_GPIOC27_XANADU_ALPHA,
	PAD_GPIOC28_XANADU_ALPHA, PAD_GPIOC29_XANADU_ALPHA, PAD_GPIOC30_XANADU_ALPHA, PAD_GPIOC31_XANADU_ALPHA,
	},
	/* GPIO group D */
	{
	PAD_GPIOD00_XANADU_ALPHA, PAD_GPIOD01_XANADU_ALPHA, PAD_GPIOD02_XANADU_ALPHA, PAD_GPIOD03_XANADU_ALPHA,
	PAD_GPIOD04_XANADU_ALPHA, PAD_GPIOD05_XANADU_ALPHA, PAD_GPIOD06_XANADU_ALPHA, PAD_GPIOD07_XANADU_ALPHA,
	PAD_GPIOD08_XANADU_ALPHA, PAD_GPIOD09_XANADU_ALPHA, PAD_GPIOD10_XANADU_ALPHA, PAD_GPIOD11_XANADU_ALPHA,
	PAD_GPIOD12_XANADU_ALPHA, PAD_GPIOD13_XANADU_ALPHA, PAD_GPIOD14_XANADU_ALPHA, PAD_GPIOD15_XANADU_ALPHA,
	PAD_GPIOD16_XANADU_ALPHA, PAD_GPIOD17_XANADU_ALPHA, PAD_GPIOD18_XANADU_ALPHA, PAD_GPIOD19_XANADU_ALPHA,
	PAD_GPIOD20_XANADU_ALPHA, PAD_GPIOD21_XANADU_ALPHA, PAD_GPIOD22_XANADU_ALPHA, PAD_GPIOD23_XANADU_ALPHA,
	PAD_GPIOD24_XANADU_ALPHA, PAD_GPIOD25_XANADU_ALPHA, PAD_GPIOD26_XANADU_ALPHA, PAD_GPIOD27_XANADU_ALPHA,
	PAD_GPIOD28_XANADU_ALPHA, PAD_GPIOD29_XANADU_ALPHA, PAD_GPIOD30_XANADU_ALPHA, PAD_GPIOD31_XANADU_ALPHA,
	},
	/* GPIO group E */
	{
	PAD_GPIOE00_XANADU_ALPHA, PAD_GPIOE01_XANADU_ALPHA, PAD_GPIOE02_XANADU_ALPHA, PAD_GPIOE03_XANADU_ALPHA,
	PAD_GPIOE04_XANADU_ALPHA, PAD_GPIOE05_XANADU_ALPHA, PAD_GPIOE06_XANADU_ALPHA, PAD_GPIOE07_XANADU_ALPHA,
	PAD_GPIOE08_XANADU_ALPHA, PAD_GPIOE09_XANADU_ALPHA, PAD_GPIOE10_XANADU_ALPHA, PAD_GPIOE11_XANADU_ALPHA,
	PAD_GPIOE12_XANADU_ALPHA, PAD_GPIOE13_XANADU_ALPHA, PAD_GPIOE14_XANADU_ALPHA, PAD_GPIOE15_XANADU_ALPHA,
	PAD_GPIOE16_XANADU_ALPHA, PAD_GPIOE17_XANADU_ALPHA, PAD_GPIOE18_XANADU_ALPHA, PAD_GPIOE19_XANADU_ALPHA,
	PAD_GPIOE20_XANADU_ALPHA, PAD_GPIOE21_XANADU_ALPHA, PAD_GPIOE22_XANADU_ALPHA, PAD_GPIOE23_XANADU_ALPHA,
	PAD_GPIOE24_XANADU_ALPHA, PAD_GPIOE25_XANADU_ALPHA, PAD_GPIOE26_XANADU_ALPHA, PAD_GPIOE27_XANADU_ALPHA,
	PAD_GPIOE28_XANADU_ALPHA, PAD_GPIOE29_XANADU_ALPHA, PAD_GPIOE30_XANADU_ALPHA, PAD_GPIOE31_XANADU_ALPHA,
	},
};

const U32 alv_pad_xanadu_alpha[8] = {
	PAD_GPIOALV00_XANADU_ALPHA, PAD_GPIOALV01_XANADU_ALPHA, PAD_GPIOALV02_XANADU_ALPHA, PAD_GPIOALV03_XANADU_ALPHA,
	PAD_GPIOALV04_XANADU_ALPHA, PAD_GPIOALV05_XANADU_ALPHA,
	};

const U32 bus_pad_xanadu_alpha[6] = {
	PAD_BUS_STATIC_CNTL_XANADU_ALPHA, PAD_BUS_STATIC_ADDR_XANADU_ALPHA, PAD_BUS_STATIC_DATA_XANADU_ALPHA,
	PAD_BUS_VSYNC_XANADU_ALPHA, PAD_BUS_HSYNC_XANADU_ALPHA, PAD_BUS_DE_XANADU_ALPHA
};
