
#include <cfg_type.h>
#include <../../glasgow/include/cfg_gpio_glasgow_alpha.h>

const U32 io_pad_glasgow_alpha[NUMBER_OF_GPIO_MODULE][32] = {
	/* GPIO group A */
	{
	PAD_GPIOA00_GLASGOW_ALPHA, PAD_GPIOA01_GLASGOW_ALPHA, PAD_GPIOA02_GLASGOW_ALPHA, PAD_GPIOA03_GLASGOW_ALPHA,
	PAD_GPIOA04_GLASGOW_ALPHA, PAD_GPIOA05_GLASGOW_ALPHA, PAD_GPIOA06_GLASGOW_ALPHA, PAD_GPIOA07_GLASGOW_ALPHA,
	PAD_GPIOA08_GLASGOW_ALPHA, PAD_GPIOA09_GLASGOW_ALPHA, PAD_GPIOA10_GLASGOW_ALPHA, PAD_GPIOA11_GLASGOW_ALPHA,
	PAD_GPIOA12_GLASGOW_ALPHA, PAD_GPIOA13_GLASGOW_ALPHA, PAD_GPIOA14_GLASGOW_ALPHA, PAD_GPIOA15_GLASGOW_ALPHA,
	PAD_GPIOA16_GLASGOW_ALPHA, PAD_GPIOA17_GLASGOW_ALPHA, PAD_GPIOA18_GLASGOW_ALPHA, PAD_GPIOA19_GLASGOW_ALPHA,
	PAD_GPIOA20_GLASGOW_ALPHA, PAD_GPIOA21_GLASGOW_ALPHA, PAD_GPIOA22_GLASGOW_ALPHA, PAD_GPIOA23_GLASGOW_ALPHA,
	PAD_GPIOA24_GLASGOW_ALPHA, PAD_GPIOA25_GLASGOW_ALPHA, PAD_GPIOA26_GLASGOW_ALPHA, PAD_GPIOA27_GLASGOW_ALPHA,
	PAD_GPIOA28_GLASGOW_ALPHA, PAD_GPIOA29_GLASGOW_ALPHA, PAD_GPIOA30_GLASGOW_ALPHA, PAD_GPIOA31_GLASGOW_ALPHA,
	},
	/* GPIO group B */
	{
	PAD_GPIOB00_GLASGOW_ALPHA, PAD_GPIOB01_GLASGOW_ALPHA, PAD_GPIOB02_GLASGOW_ALPHA, PAD_GPIOB03_GLASGOW_ALPHA,
	PAD_GPIOB04_GLASGOW_ALPHA, PAD_GPIOB05_GLASGOW_ALPHA, PAD_GPIOB06_GLASGOW_ALPHA, PAD_GPIOB07_GLASGOW_ALPHA,
	PAD_GPIOB08_GLASGOW_ALPHA, PAD_GPIOB09_GLASGOW_ALPHA, PAD_GPIOB10_GLASGOW_ALPHA, PAD_GPIOB11_GLASGOW_ALPHA,
	PAD_GPIOB12_GLASGOW_ALPHA, PAD_GPIOB13_GLASGOW_ALPHA, PAD_GPIOB14_GLASGOW_ALPHA, PAD_GPIOB15_GLASGOW_ALPHA,
	PAD_GPIOB16_GLASGOW_ALPHA, PAD_GPIOB17_GLASGOW_ALPHA, PAD_GPIOB18_GLASGOW_ALPHA, PAD_GPIOB19_GLASGOW_ALPHA,
	PAD_GPIOB20_GLASGOW_ALPHA, PAD_GPIOB21_GLASGOW_ALPHA, PAD_GPIOB22_GLASGOW_ALPHA, PAD_GPIOB23_GLASGOW_ALPHA,
	PAD_GPIOB24_GLASGOW_ALPHA, PAD_GPIOB25_GLASGOW_ALPHA, PAD_GPIOB26_GLASGOW_ALPHA, PAD_GPIOB27_GLASGOW_ALPHA,
	PAD_GPIOB28_GLASGOW_ALPHA, PAD_GPIOB29_GLASGOW_ALPHA, PAD_GPIOB30_GLASGOW_ALPHA, PAD_GPIOB31_GLASGOW_ALPHA,
	},
	/* GPIO group C */
	{
	PAD_GPIOC00_GLASGOW_ALPHA, PAD_GPIOC01_GLASGOW_ALPHA, PAD_GPIOC02_GLASGOW_ALPHA, PAD_GPIOC03_GLASGOW_ALPHA,
	PAD_GPIOC04_GLASGOW_ALPHA, PAD_GPIOC05_GLASGOW_ALPHA, PAD_GPIOC06_GLASGOW_ALPHA, PAD_GPIOC07_GLASGOW_ALPHA,
	PAD_GPIOC08_GLASGOW_ALPHA, PAD_GPIOC09_GLASGOW_ALPHA, PAD_GPIOC10_GLASGOW_ALPHA, PAD_GPIOC11_GLASGOW_ALPHA,
	PAD_GPIOC12_GLASGOW_ALPHA, PAD_GPIOC13_GLASGOW_ALPHA, PAD_GPIOC14_GLASGOW_ALPHA, PAD_GPIOC15_GLASGOW_ALPHA,
	PAD_GPIOC16_GLASGOW_ALPHA, PAD_GPIOC17_GLASGOW_ALPHA, PAD_GPIOC18_GLASGOW_ALPHA, PAD_GPIOC19_GLASGOW_ALPHA,
	PAD_GPIOC20_GLASGOW_ALPHA, PAD_GPIOC21_GLASGOW_ALPHA, PAD_GPIOC22_GLASGOW_ALPHA, PAD_GPIOC23_GLASGOW_ALPHA,
	PAD_GPIOC24_GLASGOW_ALPHA, PAD_GPIOC25_GLASGOW_ALPHA, PAD_GPIOC26_GLASGOW_ALPHA, PAD_GPIOC27_GLASGOW_ALPHA,
	PAD_GPIOC28_GLASGOW_ALPHA, PAD_GPIOC29_GLASGOW_ALPHA, PAD_GPIOC30_GLASGOW_ALPHA, PAD_GPIOC31_GLASGOW_ALPHA,
	},
	/* GPIO group D */
	{
	PAD_GPIOD00_GLASGOW_ALPHA, PAD_GPIOD01_GLASGOW_ALPHA, PAD_GPIOD02_GLASGOW_ALPHA, PAD_GPIOD03_GLASGOW_ALPHA,
	PAD_GPIOD04_GLASGOW_ALPHA, PAD_GPIOD05_GLASGOW_ALPHA, PAD_GPIOD06_GLASGOW_ALPHA, PAD_GPIOD07_GLASGOW_ALPHA,
	PAD_GPIOD08_GLASGOW_ALPHA, PAD_GPIOD09_GLASGOW_ALPHA, PAD_GPIOD10_GLASGOW_ALPHA, PAD_GPIOD11_GLASGOW_ALPHA,
	PAD_GPIOD12_GLASGOW_ALPHA, PAD_GPIOD13_GLASGOW_ALPHA, PAD_GPIOD14_GLASGOW_ALPHA, PAD_GPIOD15_GLASGOW_ALPHA,
	PAD_GPIOD16_GLASGOW_ALPHA, PAD_GPIOD17_GLASGOW_ALPHA, PAD_GPIOD18_GLASGOW_ALPHA, PAD_GPIOD19_GLASGOW_ALPHA,
	PAD_GPIOD20_GLASGOW_ALPHA, PAD_GPIOD21_GLASGOW_ALPHA, PAD_GPIOD22_GLASGOW_ALPHA, PAD_GPIOD23_GLASGOW_ALPHA,
	PAD_GPIOD24_GLASGOW_ALPHA, PAD_GPIOD25_GLASGOW_ALPHA, PAD_GPIOD26_GLASGOW_ALPHA, PAD_GPIOD27_GLASGOW_ALPHA,
	PAD_GPIOD28_GLASGOW_ALPHA, PAD_GPIOD29_GLASGOW_ALPHA, PAD_GPIOD30_GLASGOW_ALPHA, PAD_GPIOD31_GLASGOW_ALPHA,
	},
	/* GPIO group E */
	{
	PAD_GPIOE00_GLASGOW_ALPHA, PAD_GPIOE01_GLASGOW_ALPHA, PAD_GPIOE02_GLASGOW_ALPHA, PAD_GPIOE03_GLASGOW_ALPHA,
	PAD_GPIOE04_GLASGOW_ALPHA, PAD_GPIOE05_GLASGOW_ALPHA, PAD_GPIOE06_GLASGOW_ALPHA, PAD_GPIOE07_GLASGOW_ALPHA,
	PAD_GPIOE08_GLASGOW_ALPHA, PAD_GPIOE09_GLASGOW_ALPHA, PAD_GPIOE10_GLASGOW_ALPHA, PAD_GPIOE11_GLASGOW_ALPHA,
	PAD_GPIOE12_GLASGOW_ALPHA, PAD_GPIOE13_GLASGOW_ALPHA, PAD_GPIOE14_GLASGOW_ALPHA, PAD_GPIOE15_GLASGOW_ALPHA,
	PAD_GPIOE16_GLASGOW_ALPHA, PAD_GPIOE17_GLASGOW_ALPHA, PAD_GPIOE18_GLASGOW_ALPHA, PAD_GPIOE19_GLASGOW_ALPHA,
	PAD_GPIOE20_GLASGOW_ALPHA, PAD_GPIOE21_GLASGOW_ALPHA, PAD_GPIOE22_GLASGOW_ALPHA, PAD_GPIOE23_GLASGOW_ALPHA,
	PAD_GPIOE24_GLASGOW_ALPHA, PAD_GPIOE25_GLASGOW_ALPHA, PAD_GPIOE26_GLASGOW_ALPHA, PAD_GPIOE27_GLASGOW_ALPHA,
	PAD_GPIOE28_GLASGOW_ALPHA, PAD_GPIOE29_GLASGOW_ALPHA, PAD_GPIOE30_GLASGOW_ALPHA, PAD_GPIOE31_GLASGOW_ALPHA,
	},
};

const U32 alv_pad_glasgow_alpha[ALVPADS] = {
	PAD_GPIOALV00_GLASGOW_ALPHA, PAD_GPIOALV01_GLASGOW_ALPHA, 
	PAD_GPIOALV02_GLASGOW_ALPHA, PAD_GPIOALV03_GLASGOW_ALPHA,
	PAD_GPIOALV04_GLASGOW_ALPHA, PAD_GPIOALV05_GLASGOW_ALPHA
	};

const U32 bus_pad_glasgow_alpha[6] = {
	PAD_BUS_STATIC_CNTL_GLASGOW_ALPHA, PAD_BUS_STATIC_ADDR_GLASGOW_ALPHA, PAD_BUS_STATIC_DATA_GLASGOW_ALPHA,
	PAD_BUS_VSYNC_GLASGOW_ALPHA, PAD_BUS_HSYNC_GLASGOW_ALPHA, PAD_BUS_DE_GLASGOW_ALPHA
};
