
#include <cfg_type.h>
#include <../../quito/include/cfg_gpio_quito_alpha.h>

const U32 io_pad_quito_alpha[NUMBER_OF_GPIO_MODULE][32] = {
	/* GPIO group A */
	{
	PAD_GPIOA00_QUITO_ALPHA, PAD_GPIOA01_QUITO_ALPHA, PAD_GPIOA02_QUITO_ALPHA, PAD_GPIOA03_QUITO_ALPHA,
	PAD_GPIOA04_QUITO_ALPHA, PAD_GPIOA05_QUITO_ALPHA, PAD_GPIOA06_QUITO_ALPHA, PAD_GPIOA07_QUITO_ALPHA,
	PAD_GPIOA08_QUITO_ALPHA, PAD_GPIOA09_QUITO_ALPHA, PAD_GPIOA10_QUITO_ALPHA, PAD_GPIOA11_QUITO_ALPHA,
	PAD_GPIOA12_QUITO_ALPHA, PAD_GPIOA13_QUITO_ALPHA, PAD_GPIOA14_QUITO_ALPHA, PAD_GPIOA15_QUITO_ALPHA,
	PAD_GPIOA16_QUITO_ALPHA, PAD_GPIOA17_QUITO_ALPHA, PAD_GPIOA18_QUITO_ALPHA, PAD_GPIOA19_QUITO_ALPHA,
	PAD_GPIOA20_QUITO_ALPHA, PAD_GPIOA21_QUITO_ALPHA, PAD_GPIOA22_QUITO_ALPHA, PAD_GPIOA23_QUITO_ALPHA,
	PAD_GPIOA24_QUITO_ALPHA, PAD_GPIOA25_QUITO_ALPHA, PAD_GPIOA26_QUITO_ALPHA, PAD_GPIOA27_QUITO_ALPHA,
	PAD_GPIOA28_QUITO_ALPHA, PAD_GPIOA29_QUITO_ALPHA, PAD_GPIOA30_QUITO_ALPHA, PAD_GPIOA31_QUITO_ALPHA,
	},
	/* GPIO group B */
	{
	PAD_GPIOB00_QUITO_ALPHA, PAD_GPIOB01_QUITO_ALPHA, PAD_GPIOB02_QUITO_ALPHA, PAD_GPIOB03_QUITO_ALPHA,
	PAD_GPIOB04_QUITO_ALPHA, PAD_GPIOB05_QUITO_ALPHA, PAD_GPIOB06_QUITO_ALPHA, PAD_GPIOB07_QUITO_ALPHA,
	PAD_GPIOB08_QUITO_ALPHA, PAD_GPIOB09_QUITO_ALPHA, PAD_GPIOB10_QUITO_ALPHA, PAD_GPIOB11_QUITO_ALPHA,
	PAD_GPIOB12_QUITO_ALPHA, PAD_GPIOB13_QUITO_ALPHA, PAD_GPIOB14_QUITO_ALPHA, PAD_GPIOB15_QUITO_ALPHA,
	PAD_GPIOB16_QUITO_ALPHA, PAD_GPIOB17_QUITO_ALPHA, PAD_GPIOB18_QUITO_ALPHA, PAD_GPIOB19_QUITO_ALPHA,
	PAD_GPIOB20_QUITO_ALPHA, PAD_GPIOB21_QUITO_ALPHA, PAD_GPIOB22_QUITO_ALPHA, PAD_GPIOB23_QUITO_ALPHA,
	PAD_GPIOB24_QUITO_ALPHA, PAD_GPIOB25_QUITO_ALPHA, PAD_GPIOB26_QUITO_ALPHA, PAD_GPIOB27_QUITO_ALPHA,
	PAD_GPIOB28_QUITO_ALPHA, PAD_GPIOB29_QUITO_ALPHA, PAD_GPIOB30_QUITO_ALPHA, PAD_GPIOB31_QUITO_ALPHA,
	},
	/* GPIO group C */
	{
	PAD_GPIOC00_QUITO_ALPHA, PAD_GPIOC01_QUITO_ALPHA, PAD_GPIOC02_QUITO_ALPHA, PAD_GPIOC03_QUITO_ALPHA,
	PAD_GPIOC04_QUITO_ALPHA, PAD_GPIOC05_QUITO_ALPHA, PAD_GPIOC06_QUITO_ALPHA, PAD_GPIOC07_QUITO_ALPHA,
	PAD_GPIOC08_QUITO_ALPHA, PAD_GPIOC09_QUITO_ALPHA, PAD_GPIOC10_QUITO_ALPHA, PAD_GPIOC11_QUITO_ALPHA,
	PAD_GPIOC12_QUITO_ALPHA, PAD_GPIOC13_QUITO_ALPHA, PAD_GPIOC14_QUITO_ALPHA, PAD_GPIOC15_QUITO_ALPHA,
	PAD_GPIOC16_QUITO_ALPHA, PAD_GPIOC17_QUITO_ALPHA, PAD_GPIOC18_QUITO_ALPHA, PAD_GPIOC19_QUITO_ALPHA,
	PAD_GPIOC20_QUITO_ALPHA, PAD_GPIOC21_QUITO_ALPHA, PAD_GPIOC22_QUITO_ALPHA, PAD_GPIOC23_QUITO_ALPHA,
	PAD_GPIOC24_QUITO_ALPHA, PAD_GPIOC25_QUITO_ALPHA, PAD_GPIOC26_QUITO_ALPHA, PAD_GPIOC27_QUITO_ALPHA,
	PAD_GPIOC28_QUITO_ALPHA, PAD_GPIOC29_QUITO_ALPHA, PAD_GPIOC30_QUITO_ALPHA, PAD_GPIOC31_QUITO_ALPHA,
	},
	/* GPIO group D */
	{
	PAD_GPIOD00_QUITO_ALPHA, PAD_GPIOD01_QUITO_ALPHA, PAD_GPIOD02_QUITO_ALPHA, PAD_GPIOD03_QUITO_ALPHA,
	PAD_GPIOD04_QUITO_ALPHA, PAD_GPIOD05_QUITO_ALPHA, PAD_GPIOD06_QUITO_ALPHA, PAD_GPIOD07_QUITO_ALPHA,
	PAD_GPIOD08_QUITO_ALPHA, PAD_GPIOD09_QUITO_ALPHA, PAD_GPIOD10_QUITO_ALPHA, PAD_GPIOD11_QUITO_ALPHA,
	PAD_GPIOD12_QUITO_ALPHA, PAD_GPIOD13_QUITO_ALPHA, PAD_GPIOD14_QUITO_ALPHA, PAD_GPIOD15_QUITO_ALPHA,
	PAD_GPIOD16_QUITO_ALPHA, PAD_GPIOD17_QUITO_ALPHA, PAD_GPIOD18_QUITO_ALPHA, PAD_GPIOD19_QUITO_ALPHA,
	PAD_GPIOD20_QUITO_ALPHA, PAD_GPIOD21_QUITO_ALPHA, PAD_GPIOD22_QUITO_ALPHA, PAD_GPIOD23_QUITO_ALPHA,
	PAD_GPIOD24_QUITO_ALPHA, PAD_GPIOD25_QUITO_ALPHA, PAD_GPIOD26_QUITO_ALPHA, PAD_GPIOD27_QUITO_ALPHA,
	PAD_GPIOD28_QUITO_ALPHA, PAD_GPIOD29_QUITO_ALPHA, PAD_GPIOD30_QUITO_ALPHA, PAD_GPIOD31_QUITO_ALPHA,
	},
	/* GPIO group E */
	{
	PAD_GPIOE00_QUITO_ALPHA, PAD_GPIOE01_QUITO_ALPHA, PAD_GPIOE02_QUITO_ALPHA, PAD_GPIOE03_QUITO_ALPHA,
	PAD_GPIOE04_QUITO_ALPHA, PAD_GPIOE05_QUITO_ALPHA, PAD_GPIOE06_QUITO_ALPHA, PAD_GPIOE07_QUITO_ALPHA,
	PAD_GPIOE08_QUITO_ALPHA, PAD_GPIOE09_QUITO_ALPHA, PAD_GPIOE10_QUITO_ALPHA, PAD_GPIOE11_QUITO_ALPHA,
	PAD_GPIOE12_QUITO_ALPHA, PAD_GPIOE13_QUITO_ALPHA, PAD_GPIOE14_QUITO_ALPHA, PAD_GPIOE15_QUITO_ALPHA,
	PAD_GPIOE16_QUITO_ALPHA, PAD_GPIOE17_QUITO_ALPHA, PAD_GPIOE18_QUITO_ALPHA, PAD_GPIOE19_QUITO_ALPHA,
	PAD_GPIOE20_QUITO_ALPHA, PAD_GPIOE21_QUITO_ALPHA, PAD_GPIOE22_QUITO_ALPHA, PAD_GPIOE23_QUITO_ALPHA,
	PAD_GPIOE24_QUITO_ALPHA, PAD_GPIOE25_QUITO_ALPHA, PAD_GPIOE26_QUITO_ALPHA, PAD_GPIOE27_QUITO_ALPHA,
	PAD_GPIOE28_QUITO_ALPHA, PAD_GPIOE29_QUITO_ALPHA, PAD_GPIOE30_QUITO_ALPHA, PAD_GPIOE31_QUITO_ALPHA,
	},
};

const U32 alv_pad_quito_alpha[ALVPADS] =
{
	PAD_GPIOALV00_QUITO_ALPHA, PAD_GPIOALV01_QUITO_ALPHA,
	PAD_GPIOALV02_QUITO_ALPHA, PAD_GPIOALV03_QUITO_ALPHA,
	PAD_GPIOALV04_QUITO_ALPHA, PAD_GPIOALV05_QUITO_ALPHA
	};

const U32 bus_pad_quito_alpha[6] = {
	PAD_BUS_STATIC_CNTL_QUITO_ALPHA, PAD_BUS_STATIC_ADDR_QUITO_ALPHA, PAD_BUS_STATIC_DATA_QUITO_ALPHA,
	PAD_BUS_VSYNC_QUITO_ALPHA, PAD_BUS_HSYNC_QUITO_ALPHA, PAD_BUS_DE_QUITO_ALPHA
};
