
#include <cfg_type.h>
#include <../../cabo/include/cfg_gpio_cabo_alpha.h>

const U32 io_pad_cabo_alpha[NUMBER_OF_GPIO_MODULE][32] = {
	/* GPIO group A */
	{
	PAD_GPIOA00_CABO_ALPHA, PAD_GPIOA01_CABO_ALPHA, PAD_GPIOA02_CABO_ALPHA, PAD_GPIOA03_CABO_ALPHA,
	PAD_GPIOA04_CABO_ALPHA, PAD_GPIOA05_CABO_ALPHA, PAD_GPIOA06_CABO_ALPHA, PAD_GPIOA07_CABO_ALPHA,
	PAD_GPIOA08_CABO_ALPHA, PAD_GPIOA09_CABO_ALPHA, PAD_GPIOA10_CABO_ALPHA, PAD_GPIOA11_CABO_ALPHA,
	PAD_GPIOA12_CABO_ALPHA, PAD_GPIOA13_CABO_ALPHA, PAD_GPIOA14_CABO_ALPHA, PAD_GPIOA15_CABO_ALPHA,
	PAD_GPIOA16_CABO_ALPHA, PAD_GPIOA17_CABO_ALPHA, PAD_GPIOA18_CABO_ALPHA, PAD_GPIOA19_CABO_ALPHA,
	PAD_GPIOA20_CABO_ALPHA, PAD_GPIOA21_CABO_ALPHA, PAD_GPIOA22_CABO_ALPHA, PAD_GPIOA23_CABO_ALPHA,
	PAD_GPIOA24_CABO_ALPHA, PAD_GPIOA25_CABO_ALPHA, PAD_GPIOA26_CABO_ALPHA, PAD_GPIOA27_CABO_ALPHA,
	PAD_GPIOA28_CABO_ALPHA, PAD_GPIOA29_CABO_ALPHA, PAD_GPIOA30_CABO_ALPHA, PAD_GPIOA31_CABO_ALPHA,
	},
	/* GPIO group B */
	{
	PAD_GPIOB00_CABO_ALPHA, PAD_GPIOB01_CABO_ALPHA, PAD_GPIOB02_CABO_ALPHA, PAD_GPIOB03_CABO_ALPHA,
	PAD_GPIOB04_CABO_ALPHA, PAD_GPIOB05_CABO_ALPHA, PAD_GPIOB06_CABO_ALPHA, PAD_GPIOB07_CABO_ALPHA,
	PAD_GPIOB08_CABO_ALPHA, PAD_GPIOB09_CABO_ALPHA, PAD_GPIOB10_CABO_ALPHA, PAD_GPIOB11_CABO_ALPHA,
	PAD_GPIOB12_CABO_ALPHA, PAD_GPIOB13_CABO_ALPHA, PAD_GPIOB14_CABO_ALPHA, PAD_GPIOB15_CABO_ALPHA,
	PAD_GPIOB16_CABO_ALPHA, PAD_GPIOB17_CABO_ALPHA, PAD_GPIOB18_CABO_ALPHA, PAD_GPIOB19_CABO_ALPHA,
	PAD_GPIOB20_CABO_ALPHA, PAD_GPIOB21_CABO_ALPHA, PAD_GPIOB22_CABO_ALPHA, PAD_GPIOB23_CABO_ALPHA,
	PAD_GPIOB24_CABO_ALPHA, PAD_GPIOB25_CABO_ALPHA, PAD_GPIOB26_CABO_ALPHA, PAD_GPIOB27_CABO_ALPHA,
	PAD_GPIOB28_CABO_ALPHA, PAD_GPIOB29_CABO_ALPHA, PAD_GPIOB30_CABO_ALPHA, PAD_GPIOB31_CABO_ALPHA,
	},
	/* GPIO group C */
	{
	PAD_GPIOC00_CABO_ALPHA, PAD_GPIOC01_CABO_ALPHA, PAD_GPIOC02_CABO_ALPHA, PAD_GPIOC03_CABO_ALPHA,
	PAD_GPIOC04_CABO_ALPHA, PAD_GPIOC05_CABO_ALPHA, PAD_GPIOC06_CABO_ALPHA, PAD_GPIOC07_CABO_ALPHA,
	PAD_GPIOC08_CABO_ALPHA, PAD_GPIOC09_CABO_ALPHA, PAD_GPIOC10_CABO_ALPHA, PAD_GPIOC11_CABO_ALPHA,
	PAD_GPIOC12_CABO_ALPHA, PAD_GPIOC13_CABO_ALPHA, PAD_GPIOC14_CABO_ALPHA, PAD_GPIOC15_CABO_ALPHA,
	PAD_GPIOC16_CABO_ALPHA, PAD_GPIOC17_CABO_ALPHA, PAD_GPIOC18_CABO_ALPHA, PAD_GPIOC19_CABO_ALPHA,
	PAD_GPIOC20_CABO_ALPHA, PAD_GPIOC21_CABO_ALPHA, PAD_GPIOC22_CABO_ALPHA, PAD_GPIOC23_CABO_ALPHA,
	PAD_GPIOC24_CABO_ALPHA, PAD_GPIOC25_CABO_ALPHA, PAD_GPIOC26_CABO_ALPHA, PAD_GPIOC27_CABO_ALPHA,
	PAD_GPIOC28_CABO_ALPHA, PAD_GPIOC29_CABO_ALPHA, PAD_GPIOC30_CABO_ALPHA, PAD_GPIOC31_CABO_ALPHA,
	},
	/* GPIO group D */
	{
	PAD_GPIOD00_CABO_ALPHA, PAD_GPIOD01_CABO_ALPHA, PAD_GPIOD02_CABO_ALPHA, PAD_GPIOD03_CABO_ALPHA,
	PAD_GPIOD04_CABO_ALPHA, PAD_GPIOD05_CABO_ALPHA, PAD_GPIOD06_CABO_ALPHA, PAD_GPIOD07_CABO_ALPHA,
	PAD_GPIOD08_CABO_ALPHA, PAD_GPIOD09_CABO_ALPHA, PAD_GPIOD10_CABO_ALPHA, PAD_GPIOD11_CABO_ALPHA,
	PAD_GPIOD12_CABO_ALPHA, PAD_GPIOD13_CABO_ALPHA, PAD_GPIOD14_CABO_ALPHA, PAD_GPIOD15_CABO_ALPHA,
	PAD_GPIOD16_CABO_ALPHA, PAD_GPIOD17_CABO_ALPHA, PAD_GPIOD18_CABO_ALPHA, PAD_GPIOD19_CABO_ALPHA,
	PAD_GPIOD20_CABO_ALPHA, PAD_GPIOD21_CABO_ALPHA, PAD_GPIOD22_CABO_ALPHA, PAD_GPIOD23_CABO_ALPHA,
	PAD_GPIOD24_CABO_ALPHA, PAD_GPIOD25_CABO_ALPHA, PAD_GPIOD26_CABO_ALPHA, PAD_GPIOD27_CABO_ALPHA,
	PAD_GPIOD28_CABO_ALPHA, PAD_GPIOD29_CABO_ALPHA, PAD_GPIOD30_CABO_ALPHA, PAD_GPIOD31_CABO_ALPHA,
	},
	/* GPIO group E */
	{
	PAD_GPIOE00_CABO_ALPHA, PAD_GPIOE01_CABO_ALPHA, PAD_GPIOE02_CABO_ALPHA, PAD_GPIOE03_CABO_ALPHA,
	PAD_GPIOE04_CABO_ALPHA, PAD_GPIOE05_CABO_ALPHA, PAD_GPIOE06_CABO_ALPHA, PAD_GPIOE07_CABO_ALPHA,
	PAD_GPIOE08_CABO_ALPHA, PAD_GPIOE09_CABO_ALPHA, PAD_GPIOE10_CABO_ALPHA, PAD_GPIOE11_CABO_ALPHA,
	PAD_GPIOE12_CABO_ALPHA, PAD_GPIOE13_CABO_ALPHA, PAD_GPIOE14_CABO_ALPHA, PAD_GPIOE15_CABO_ALPHA,
	PAD_GPIOE16_CABO_ALPHA, PAD_GPIOE17_CABO_ALPHA, PAD_GPIOE18_CABO_ALPHA, PAD_GPIOE19_CABO_ALPHA,
	PAD_GPIOE20_CABO_ALPHA, PAD_GPIOE21_CABO_ALPHA, PAD_GPIOE22_CABO_ALPHA, PAD_GPIOE23_CABO_ALPHA,
	PAD_GPIOE24_CABO_ALPHA, PAD_GPIOE25_CABO_ALPHA, PAD_GPIOE26_CABO_ALPHA, PAD_GPIOE27_CABO_ALPHA,
	PAD_GPIOE28_CABO_ALPHA, PAD_GPIOE29_CABO_ALPHA, PAD_GPIOE30_CABO_ALPHA, PAD_GPIOE31_CABO_ALPHA,
	},
};

const U32 alv_pad_cabo_alpha[ALVPADS] = 
{
	PAD_GPIOALV00_CABO_ALPHA, PAD_GPIOALV01_CABO_ALPHA, 
	PAD_GPIOALV02_CABO_ALPHA, PAD_GPIOALV03_CABO_ALPHA,
	PAD_GPIOALV04_CABO_ALPHA, PAD_GPIOALV05_CABO_ALPHA
	};

const U32 bus_pad_cabo_alpha[6] = {
	PAD_BUS_STATIC_CNTL_CABO_ALPHA, PAD_BUS_STATIC_ADDR_CABO_ALPHA, PAD_BUS_STATIC_DATA_CABO_ALPHA,
	PAD_BUS_VSYNC_CABO_ALPHA, PAD_BUS_HSYNC_CABO_ALPHA, PAD_BUS_DE_CABO_ALPHA
};
