
#include <cfg_type.h>
#include <../../bogota/include/cfg_gpio_bogota_alpha.h>

const U32 io_pad_bogota_alpha[NUMBER_OF_GPIO_MODULE][32] = {
	/* GPIO group A */
	{
	PAD_GPIOA00_BOGOTA_ALPHA, PAD_GPIOA01_BOGOTA_ALPHA, PAD_GPIOA02_BOGOTA_ALPHA, PAD_GPIOA03_BOGOTA_ALPHA,
	PAD_GPIOA04_BOGOTA_ALPHA, PAD_GPIOA05_BOGOTA_ALPHA, PAD_GPIOA06_BOGOTA_ALPHA, PAD_GPIOA07_BOGOTA_ALPHA,
	PAD_GPIOA08_BOGOTA_ALPHA, PAD_GPIOA09_BOGOTA_ALPHA, PAD_GPIOA10_BOGOTA_ALPHA, PAD_GPIOA11_BOGOTA_ALPHA,
	PAD_GPIOA12_BOGOTA_ALPHA, PAD_GPIOA13_BOGOTA_ALPHA, PAD_GPIOA14_BOGOTA_ALPHA, PAD_GPIOA15_BOGOTA_ALPHA,
	PAD_GPIOA16_BOGOTA_ALPHA, PAD_GPIOA17_BOGOTA_ALPHA, PAD_GPIOA18_BOGOTA_ALPHA, PAD_GPIOA19_BOGOTA_ALPHA,
	PAD_GPIOA20_BOGOTA_ALPHA, PAD_GPIOA21_BOGOTA_ALPHA, PAD_GPIOA22_BOGOTA_ALPHA, PAD_GPIOA23_BOGOTA_ALPHA,
	PAD_GPIOA24_BOGOTA_ALPHA, PAD_GPIOA25_BOGOTA_ALPHA, PAD_GPIOA26_BOGOTA_ALPHA, PAD_GPIOA27_BOGOTA_ALPHA,
	PAD_GPIOA28_BOGOTA_ALPHA, PAD_GPIOA29_BOGOTA_ALPHA, PAD_GPIOA30_BOGOTA_ALPHA, PAD_GPIOA31_BOGOTA_ALPHA,
	},
	/* GPIO group B */
	{
	PAD_GPIOB00_BOGOTA_ALPHA, PAD_GPIOB01_BOGOTA_ALPHA, PAD_GPIOB02_BOGOTA_ALPHA, PAD_GPIOB03_BOGOTA_ALPHA,
	PAD_GPIOB04_BOGOTA_ALPHA, PAD_GPIOB05_BOGOTA_ALPHA, PAD_GPIOB06_BOGOTA_ALPHA, PAD_GPIOB07_BOGOTA_ALPHA,
	PAD_GPIOB08_BOGOTA_ALPHA, PAD_GPIOB09_BOGOTA_ALPHA, PAD_GPIOB10_BOGOTA_ALPHA, PAD_GPIOB11_BOGOTA_ALPHA,
	PAD_GPIOB12_BOGOTA_ALPHA, PAD_GPIOB13_BOGOTA_ALPHA, PAD_GPIOB14_BOGOTA_ALPHA, PAD_GPIOB15_BOGOTA_ALPHA,
	PAD_GPIOB16_BOGOTA_ALPHA, PAD_GPIOB17_BOGOTA_ALPHA, PAD_GPIOB18_BOGOTA_ALPHA, PAD_GPIOB19_BOGOTA_ALPHA,
	PAD_GPIOB20_BOGOTA_ALPHA, PAD_GPIOB21_BOGOTA_ALPHA, PAD_GPIOB22_BOGOTA_ALPHA, PAD_GPIOB23_BOGOTA_ALPHA,
	PAD_GPIOB24_BOGOTA_ALPHA, PAD_GPIOB25_BOGOTA_ALPHA, PAD_GPIOB26_BOGOTA_ALPHA, PAD_GPIOB27_BOGOTA_ALPHA,
	PAD_GPIOB28_BOGOTA_ALPHA, PAD_GPIOB29_BOGOTA_ALPHA, PAD_GPIOB30_BOGOTA_ALPHA, PAD_GPIOB31_BOGOTA_ALPHA,
	},
	/* GPIO group C */
	{
	PAD_GPIOC00_BOGOTA_ALPHA, PAD_GPIOC01_BOGOTA_ALPHA, PAD_GPIOC02_BOGOTA_ALPHA, PAD_GPIOC03_BOGOTA_ALPHA,
	PAD_GPIOC04_BOGOTA_ALPHA, PAD_GPIOC05_BOGOTA_ALPHA, PAD_GPIOC06_BOGOTA_ALPHA, PAD_GPIOC07_BOGOTA_ALPHA,
	PAD_GPIOC08_BOGOTA_ALPHA, PAD_GPIOC09_BOGOTA_ALPHA, PAD_GPIOC10_BOGOTA_ALPHA, PAD_GPIOC11_BOGOTA_ALPHA,
	PAD_GPIOC12_BOGOTA_ALPHA, PAD_GPIOC13_BOGOTA_ALPHA, PAD_GPIOC14_BOGOTA_ALPHA, PAD_GPIOC15_BOGOTA_ALPHA,
	PAD_GPIOC16_BOGOTA_ALPHA, PAD_GPIOC17_BOGOTA_ALPHA, PAD_GPIOC18_BOGOTA_ALPHA, PAD_GPIOC19_BOGOTA_ALPHA,
	PAD_GPIOC20_BOGOTA_ALPHA, PAD_GPIOC21_BOGOTA_ALPHA, PAD_GPIOC22_BOGOTA_ALPHA, PAD_GPIOC23_BOGOTA_ALPHA,
	PAD_GPIOC24_BOGOTA_ALPHA, PAD_GPIOC25_BOGOTA_ALPHA, PAD_GPIOC26_BOGOTA_ALPHA, PAD_GPIOC27_BOGOTA_ALPHA,
	PAD_GPIOC28_BOGOTA_ALPHA, PAD_GPIOC29_BOGOTA_ALPHA, PAD_GPIOC30_BOGOTA_ALPHA, PAD_GPIOC31_BOGOTA_ALPHA,
	},
	/* GPIO group D */
	{
	PAD_GPIOD00_BOGOTA_ALPHA, PAD_GPIOD01_BOGOTA_ALPHA, PAD_GPIOD02_BOGOTA_ALPHA, PAD_GPIOD03_BOGOTA_ALPHA,
	PAD_GPIOD04_BOGOTA_ALPHA, PAD_GPIOD05_BOGOTA_ALPHA, PAD_GPIOD06_BOGOTA_ALPHA, PAD_GPIOD07_BOGOTA_ALPHA,
	PAD_GPIOD08_BOGOTA_ALPHA, PAD_GPIOD09_BOGOTA_ALPHA, PAD_GPIOD10_BOGOTA_ALPHA, PAD_GPIOD11_BOGOTA_ALPHA,
	PAD_GPIOD12_BOGOTA_ALPHA, PAD_GPIOD13_BOGOTA_ALPHA, PAD_GPIOD14_BOGOTA_ALPHA, PAD_GPIOD15_BOGOTA_ALPHA,
	PAD_GPIOD16_BOGOTA_ALPHA, PAD_GPIOD17_BOGOTA_ALPHA, PAD_GPIOD18_BOGOTA_ALPHA, PAD_GPIOD19_BOGOTA_ALPHA,
	PAD_GPIOD20_BOGOTA_ALPHA, PAD_GPIOD21_BOGOTA_ALPHA, PAD_GPIOD22_BOGOTA_ALPHA, PAD_GPIOD23_BOGOTA_ALPHA,
	PAD_GPIOD24_BOGOTA_ALPHA, PAD_GPIOD25_BOGOTA_ALPHA, PAD_GPIOD26_BOGOTA_ALPHA, PAD_GPIOD27_BOGOTA_ALPHA,
	PAD_GPIOD28_BOGOTA_ALPHA, PAD_GPIOD29_BOGOTA_ALPHA, PAD_GPIOD30_BOGOTA_ALPHA, PAD_GPIOD31_BOGOTA_ALPHA,
	},
	/* GPIO group E */
	{
	PAD_GPIOE00_BOGOTA_ALPHA, PAD_GPIOE01_BOGOTA_ALPHA, PAD_GPIOE02_BOGOTA_ALPHA, PAD_GPIOE03_BOGOTA_ALPHA,
	PAD_GPIOE04_BOGOTA_ALPHA, PAD_GPIOE05_BOGOTA_ALPHA, PAD_GPIOE06_BOGOTA_ALPHA, PAD_GPIOE07_BOGOTA_ALPHA,
	PAD_GPIOE08_BOGOTA_ALPHA, PAD_GPIOE09_BOGOTA_ALPHA, PAD_GPIOE10_BOGOTA_ALPHA, PAD_GPIOE11_BOGOTA_ALPHA,
	PAD_GPIOE12_BOGOTA_ALPHA, PAD_GPIOE13_BOGOTA_ALPHA, PAD_GPIOE14_BOGOTA_ALPHA, PAD_GPIOE15_BOGOTA_ALPHA,
	PAD_GPIOE16_BOGOTA_ALPHA, PAD_GPIOE17_BOGOTA_ALPHA, PAD_GPIOE18_BOGOTA_ALPHA, PAD_GPIOE19_BOGOTA_ALPHA,
	PAD_GPIOE20_BOGOTA_ALPHA, PAD_GPIOE21_BOGOTA_ALPHA, PAD_GPIOE22_BOGOTA_ALPHA, PAD_GPIOE23_BOGOTA_ALPHA,
	PAD_GPIOE24_BOGOTA_ALPHA, PAD_GPIOE25_BOGOTA_ALPHA, PAD_GPIOE26_BOGOTA_ALPHA, PAD_GPIOE27_BOGOTA_ALPHA,
	PAD_GPIOE28_BOGOTA_ALPHA, PAD_GPIOE29_BOGOTA_ALPHA, PAD_GPIOE30_BOGOTA_ALPHA, PAD_GPIOE31_BOGOTA_ALPHA,
	},
};

const U32 alv_pad_bogota_alpha[6] = {
	PAD_GPIOALV00_BOGOTA_ALPHA, PAD_GPIOALV01_BOGOTA_ALPHA, PAD_GPIOALV02_BOGOTA_ALPHA, PAD_GPIOALV03_BOGOTA_ALPHA,
	PAD_GPIOALV04_BOGOTA_ALPHA, PAD_GPIOALV05_BOGOTA_ALPHA, 	};

const U32 bus_pad_bogota_alpha[6] = {
	PAD_BUS_STATIC_CNTL_BOGOTA_ALPHA, PAD_BUS_STATIC_ADDR_BOGOTA_ALPHA, PAD_BUS_STATIC_DATA_BOGOTA_ALPHA,
	PAD_BUS_VSYNC_BOGOTA_ALPHA, PAD_BUS_HSYNC_BOGOTA_ALPHA, PAD_BUS_DE_BOGOTA_ALPHA
};
