
obj-$(CONFIG_GPIO_LEAPFROG)	+= gpio-lf.o gpio_map.o

obj-$(CONFIG_ARCH_NXP4330)	+=	init_gpio.o \
					cfg_gpio_bogota_alpha.o \
					cfg_gpio_cabo_alpha.o \
					cfg_gpio_glasgow_alpha.o \
					cfg_gpio_glasgow_beta.o \
					cfg_gpio_r3k.o \
					cfg_gpio_xanadu_alpha.o \
					cfg_gpio_quito_alpha.o

