static const char HI253_Capture_UXGA[][3] = {
#if 0
//page 0
{WINDOW_PAGE, PWRCTL, 0xf1}, //0x79}, //sleep on
{WINDOW_PAGE, PLLCTL1, 0x00}, //PLL off
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE}, // Dummy 750us START
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE}, // Dummy 750us END
#endif

#if 0
// PAGE 20
{WINDOW_PAGE, PAGEMODE, AUTOEXP_PAGE}, //page 20
{AUTOEXP_PAGE, AECTL1, 0x1c}, //ae off

// PAGE 22
{AUTOEXP_PAGE, PAGEMODE, AUTOWB_PAGE}, //page 22
{AUTOWB_PAGE, AWBCTL1, 0x69}, //awb off
#endif

{AUTOWB_PAGE, PAGEMODE, WINDOW_PAGE}, //Page 0
{WINDOW_PAGE, VDOCTL1, 0x00}, // Sub1/2_Preview2 Mode_H binning
{WINDOW_PAGE, VDOCTL2, FLIP(0x94)}, //Fixed FPS
{WINDOW_PAGE, SYNCCTL, 0x24},
{WINDOW_PAGE, WINROWH, 0x00}, // Windowing start point Y
{WINDOW_PAGE, WINROWL, 0x0c},
{WINDOW_PAGE, WINCOLH, 0x00}, // Windowing start point X
{WINDOW_PAGE, WINCOLL, 0x0a},
{WINDOW_PAGE, HBLANKH, 0x01}, //Hblank 360
{WINDOW_PAGE, HBLANKL, 0x68}, 
{WINDOW_PAGE, VSYNCH, 0x00}, //Vblank 20
{WINDOW_PAGE, VSYNCL, 0x14}, 

#if 0
{WINDOW_PAGE, PAGEMODE, AUTOEXP_PAGE}, //Page 20
{AUTOEXP_PAGE, EXPTIMEH, 0x01}, //EXP Normal 33.33 fps
{AUTOEXP_PAGE, EXPTIMEM, 0x8b},
{AUTOEXP_PAGE, EXPTIMEL, 0x82},
{AUTOEXP_PAGE, EXPMINH, 0x01}, //EXPMin 11250.00 fps
{AUTOEXP_PAGE, EXPMINL, 0xf4},
{AUTOEXP_PAGE, EXPMAXH, 0x0c}, //EXP Max fps
{AUTOEXP_PAGE, EXPMAXM, 0xdf},
{AUTOEXP_PAGE, EXPMAXL, 0xe6},
{AUTOEXP_PAGE, EXP100H, 0x83}, //EXP100 
{AUTOEXP_PAGE, EXP100L, 0xd6}, 
{AUTOEXP_PAGE, EXP120H, 0x6d}, //EXP120 
{AUTOEXP_PAGE, EXP120L, 0x60},
{AUTOEXP_PAGE, EXPLMTH, 0x0f}, //EXP Limit 1406.25 fps
{AUTOEXP_PAGE, EXPLMTL, 0xa0},
{AUTOEXP_PAGE, EXPUNITH, 0x01}, //EXP Unit 
{AUTOEXP_PAGE, EXPUNITL, 0xf4},

//AntiBand Unlock
{AUTOEXP_PAGE, PAGEMODE, AUTOEXP_PAGE}, //Page 20 
{AUTOEXP_PAGE, AEFINECTL4, 0x34}, 
{AUTOEXP_PAGE, 0x30, 0x78}, 
#endif

#if 0
//BLC 
{AUTOEXP_PAGE, PAGEMODE, WINDOW_PAGE}, //PAGE 0
{WINDOW_PAGE, BLCTIMETHON, 0x19}, //BLC_TIME_TH_ON
{WINDOW_PAGE, BLCTIMETHOFF, 0x19}, //BLC_TIME_TH_OFF
{WINDOW_PAGE, BLCAGTHH, 0xd8}, //BLC_AG_TH_ON
{WINDOW_PAGE, BLCAGTHL, 0xd0}, //BLC_AG_TH_OFF
//DCDC 
{WINDOW_PAGE, PAGEMODE, UNDOC_0x02_PAGE}, //PAGE 2
{UNDOC_0x02_PAGE, 0xd4, 0x06}, //DCDC_TIME_TH_ON
{UNDOC_0x02_PAGE, 0xd5, 0x06}, //DCDC_TIME_TH_OFF
{UNDOC_0x02_PAGE, 0xd6, 0x98}, //DCDC_AG_TH_ON
{UNDOC_0x02_PAGE, 0xd7, 0x90}, //DCDC_AG_TH_OFF
#endif

#if 0
{WINDOW_PAGE, PLLCTL1, 0x02}, //PLL 1.5x
{WINDOW_PAGE, PLLCTL1, 0x72}, //PLL 1.5x on
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE}, // Dummy 750us START
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE}, // Dummy 750us END
{WINDOW_PAGE, PWRCTL, 0x60}, //0x78}, //sleep off
#endif
};

static const char HI253_Capture_SVGA[][3] = {
#if 0
{WINDOW_PAGE, PWRCTL, 0xf1}, //0x79}, //sleep on
{WINDOW_PAGE, PLLCTL1, 0x00}, //PLL off
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE}, // Dummy 750us START
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE}, // Dummy 750us END
#endif

{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE}, //Page 0
{WINDOW_PAGE, VDOCTL1, 0x11}, //SVGA, preview
{WINDOW_PAGE, VDOCTL2, FLIP(0x94)}, //Fixed FPS
{WINDOW_PAGE, WINROWH, 0x00}, // Windowing start point Y
{WINDOW_PAGE, WINROWL, 0x04},
{WINDOW_PAGE, WINCOLH, 0x00}, // Windowing start point X
{WINDOW_PAGE, WINCOLL, 0x07},
{WINDOW_PAGE, HBLANKH, 0x01}, //Hblank 360
{WINDOW_PAGE, HBLANKL, 0x68},
{WINDOW_PAGE, VSYNCH, 0x00}, //Vblank 20
{WINDOW_PAGE, VSYNCL, 0x14},

#if 0
{WINDOW_PAGE, PAGEMODE, AUTOEXP_PAGE}, //Page 20
{AUTOEXP_PAGE, EXPTIMEH, 0x01}, //EXP Normal 33.33 fps
{AUTOEXP_PAGE, EXPTIMEM, 0x8b},
{AUTOEXP_PAGE, EXPTIMEL, 0x82},
{AUTOEXP_PAGE, EXPMINH, 0x01}, //EXPMin 11250.00 fps
{AUTOEXP_PAGE, EXPMINL, 0x2c},
{AUTOEXP_PAGE, EXPMAXH, 0x03}, //EXP Max fps
{AUTOEXP_PAGE, EXPMAXM, 0x17},
{AUTOEXP_PAGE, EXPMAXL, 0x04},
{AUTOEXP_PAGE, EXP100H, 0x83}, //EXP100
{AUTOEXP_PAGE, EXP100L, 0xd6},
{AUTOEXP_PAGE, EXP120H, 0x6d}, //EXP120
{AUTOEXP_PAGE, EXP120L, 0x92},
{AUTOEXP_PAGE, EXPFIXH, 0x03}, //EXP Fix 15.00 fps
{AUTOEXP_PAGE, EXPFIXM, 0x6e},
{AUTOEXP_PAGE, EXPFIXL, 0xe8},
{AUTOEXP_PAGE, EXPLMTH, 0x09}, //EXP Limit 1406.25 fps
{AUTOEXP_PAGE, EXPLMTL, 0x60},
{AUTOEXP_PAGE, EXPUNITH, 0x01}, //EXP Unit
{AUTOEXP_PAGE, EXPUNITL, 0x2c},

//AntiBand Unlock
{AUTOEXP_PAGE, PAGEMODE, AUTOEXP_PAGE}, //Page 20
{AUTOEXP_PAGE, AEFINECTL4, 0x34},
{AUTOEXP_PAGE, 0x30, 0x78},
#endif

#if 0
//Auto-Exposure on
{AUTOEXP_PAGE, AECTL1, 0x9c}, //ae on

//Auto-WhiteBalance on
{AUTOEXP_PAGE, PAGEMODE, AUTOWB_PAGE}, //page 22
{AUTOWB_PAGE, AWBCTL1, 0xe9}, //awb on
#endif

#if 0
//BLC
{AUTOEXP_PAGE, PAGEMODE, WINDOW_PAGE}, //PAGE 0
{WINDOW_PAGE, BLCTIMETHON, 0x06}, //BLC_TIME_TH_ON
{WINDOW_PAGE, BLCTIMETHOFF, 0x06}, //BLC_TIME_TH_OFF
{WINDOW_PAGE, BLCAGTHH, 0xd8}, //BLC_AG_TH_ON
{WINDOW_PAGE, BLCAGTHL, 0xd0}, //BLC_AG_TH_OFF
//DCDC
{WINDOW_PAGE, PAGEMODE, UNDOC_0x02_PAGE}, //PAGE 2
{UNDOC_0x02_PAGE, 0xd4, 0x06}, //DCDC_TIME_TH_ON
{UNDOC_0x02_PAGE, 0xd5, 0x06}, //DCDC_TIME_TH_OFF
{UNDOC_0x02_PAGE, 0xd6, 0xd8}, //DCDC_AG_TH_ON
{UNDOC_0x02_PAGE, 0xd7, 0xd0}, //DCDC_AG_TH_OFF
#endif

#if 0
{WINDOW_PAGE, PLLCTL1, PLLX(0x00)}, //PLL On
{WINDOW_PAGE, PLLCTL1, PLLX(0x70)}, //PLLx2
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE}, // Dummy 750us START
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE}, // Dummy 750us END
{WINDOW_PAGE, PWRCTL, 0x60}, //0x78}, //sleep off
#endif
};

static const char HI253_Capture_QSVGA[][3] = {
#if 0
{WINDOW_PAGE, PWRCTL, 0xf1}, //0x79}, //sleep on
{WINDOW_PAGE, PLLCTL1, 0x00}, //PLL off
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE}, // Dummy 750us START
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE}, // Dummy 750us END
#endif

{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE}, //Page 0
{WINDOW_PAGE, VDOCTL1, 0x21}, //QSVGA, preview
{WINDOW_PAGE, VDOCTL2, FLIP(0x94)}, //Fixed FPS
{WINDOW_PAGE, WINROWH, 0x00}, // Windowing start point Y
{WINDOW_PAGE, WINROWL, 0x04},
{WINDOW_PAGE, WINCOLH, 0x00}, // Windowing start point X
{WINDOW_PAGE, WINCOLL, 0x07},
{WINDOW_PAGE, HBLANKH, 0x01}, //Hblank 360
{WINDOW_PAGE, HBLANKL, 0x68},
{WINDOW_PAGE, VSYNCH, 0x00}, //Vblank 20
{WINDOW_PAGE, VSYNCL, 0x14},

#if 0
{WINDOW_PAGE, PAGEMODE, AUTOEXP_PAGE}, //Page 20
{AUTOEXP_PAGE, EXPTIMEH, 0x01}, //EXP Normal 33.33 fps
{AUTOEXP_PAGE, EXPTIMEM, 0x8b},
{AUTOEXP_PAGE, EXPTIMEL, 0x82},
{AUTOEXP_PAGE, EXPMINH, 0x01}, //EXPMin 11250.00 fps
{AUTOEXP_PAGE, EXPMINL, 0x2c},
{AUTOEXP_PAGE, EXPMAXH, 0x03}, //EXP Max fps
{AUTOEXP_PAGE, EXPMAXM, 0x17},
{AUTOEXP_PAGE, EXPMAXL, 0x04},
{AUTOEXP_PAGE, EXP100H, 0x83}, //EXP100
{AUTOEXP_PAGE, EXP100L, 0xd6},
{AUTOEXP_PAGE, EXP120H, 0x6d}, //EXP120
{AUTOEXP_PAGE, EXP120L, 0x92},
{AUTOEXP_PAGE, EXPFIXH, 0x03}, //EXP Fix 15.00 fps
{AUTOEXP_PAGE, EXPFIXM, 0x6e},
{AUTOEXP_PAGE, EXPFIXL, 0xe8},
{AUTOEXP_PAGE, EXPLMTH, 0x09}, //EXP Limit 1406.25 fps
{AUTOEXP_PAGE, EXPLMTL, 0x60},
{AUTOEXP_PAGE, EXPUNITH, 0x01}, //EXP Unit
{AUTOEXP_PAGE, EXPUNITL, 0x2c},

#if (IS_PLL_1_5X)
{AUTOEXP_PAGE, EXPFIXH, 0x02}, //EXP Fix 15.00 fps @ PLL 1.5x
{AUTOEXP_PAGE, EXPFIXM, 0x93},
{AUTOEXP_PAGE, EXPFIXL, 0x2E},
#elif (IS_PLL_2X)
{AUTOEXP_PAGE, EXPFIXH, 0x01}, // Fixed 30FPS @ PLL 2x
{AUTOEXP_PAGE, EXPFIXM, 0xb7},
{AUTOEXP_PAGE, EXPFIXL, 0x74},
#else
{AUTOEXP_PAGE, EXPFIXH, 0x03}, //EXP Fix 15.00 fps
{AUTOEXP_PAGE, EXPFIXM, 0x6e},
{AUTOEXP_PAGE, EXPFIXL, 0xe8},
#endif

//AntiBand Unlock
{AUTOEXP_PAGE, PAGEMODE, AUTOEXP_PAGE}, //Page 20
{AUTOEXP_PAGE, AEFINECTL4, 0x34},
{AUTOEXP_PAGE, 0x30, 0x78},
#endif

#if 0
//Auto-Exposure on
{AUTOEXP_PAGE, AECTL1, 0x9c}, //ae on

//Auto-WhiteBalance on
{AUTOEXP_PAGE, PAGEMODE, AUTOWB_PAGE}, //page 22
{AUTOWB_PAGE, AWBCTL1, 0xe9}, //awb on
#endif

#if 0
//BLC
{AUTOEXP_PAGE, PAGEMODE, WINDOW_PAGE}, //PAGE 0
{WINDOW_PAGE, BLCTIMETHON, 0x06}, //BLC_TIME_TH_ON
{WINDOW_PAGE, BLCTIMETHOFF, 0x06}, //BLC_TIME_TH_OFF
{WINDOW_PAGE, BLCAGTHH, 0xd8}, //BLC_AG_TH_ON
{WINDOW_PAGE, BLCAGTHL, 0xd0}, //BLC_AG_TH_OFF
//DCDC
{WINDOW_PAGE, PAGEMODE, UNDOC_0x02_PAGE}, //PAGE 2
{UNDOC_0x02_PAGE, 0xd4, 0x06}, //DCDC_TIME_TH_ON
{UNDOC_0x02_PAGE, 0xd5, 0x06}, //DCDC_TIME_TH_OFF
{UNDOC_0x02_PAGE, 0xd6, 0xd8}, //DCDC_AG_TH_ON
{UNDOC_0x02_PAGE, 0xd7, 0xd0}, //DCDC_AG_TH_OFF
#endif

#if 0
{WINDOW_PAGE, PLLCTL1, PLLX(0x00)}, //PLL On
{WINDOW_PAGE, PLLCTL1, PLLX(0x70)}, //PLLx2
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE}, // Dummy 750us START
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE},
{WINDOW_PAGE, PAGEMODE, WINDOW_PAGE}, // Dummy 750us END
{WINDOW_PAGE, PWRCTL, 0x60}, //0x78}, //sleep off
#endif
};
