#ifndef __CFG_GPIO_CABO_ALPHA_H__
#define __CFG_GPIO_CABO_ALPHA_H__

#include <mach/nxp4330.h>

/*------------------------------------------------------------------------------
*	GPIO Bank A
*/
#define PAD_GPIOA00_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: VOUT_PCLK_R */
#define PAD_GPIOA01_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD0 */
#define PAD_GPIOA02_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD1 */
#define PAD_GPIOA03_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD2 */
#define PAD_GPIOA04_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD3 */
#define PAD_GPIOA05_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD4 */
#define PAD_GPIOA06_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD5 */
#define PAD_GPIOA07_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD6 */

#define PAD_GPIOA08_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD7 */
#define PAD_GPIOA09_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD8 */
#define PAD_GPIOA10_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD9 */
#define PAD_GPIOA11_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD10 */
#define PAD_GPIOA12_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD11 */
#define PAD_GPIOA13_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD12 */
#define PAD_GPIOA14_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD13 */
#define PAD_GPIOA15_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD14 */

#define PAD_GPIOA16_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD15 */
#define PAD_GPIOA17_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD16 */
#define PAD_GPIOA18_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD17 */
#define PAD_GPIOA19_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD18 */
#define PAD_GPIOA20_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD19 */
#define PAD_GPIOA21_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD20 */
#define PAD_GPIOA22_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD21 */
#define PAD_GPIOA23_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD22 */

#define PAD_GPIOA24_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: PVD23 */
#define PAD_GPIOA25_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: VOUT_PVSYNC_R */
#define PAD_GPIOA26_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_1)		/* Pin Use: VOUT_PHSYNC_R */
#define PAD_GPIOA27_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VOUT_DE_R */
#define PAD_GPIOA28_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_PCLK */
#define PAD_GPIOA29_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCLK0_R */
#define PAD_GPIOA30_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_0 */
#define PAD_GPIOA31_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCMD0_R */
/*------------------------------------------------------------------------------
*	GPIO Bank B
*/
#define PAD_GPIOB00_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_1 */
#define PAD_GPIOB01_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT00_R */
#define PAD_GPIOB02_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_2 */
#define PAD_GPIOB03_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT01_R */
#define PAD_GPIOB04_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_3 */
#define PAD_GPIOB05_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT02_R */
#define PAD_GPIOB06_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_4 */
#define PAD_GPIOB07_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT03_R */

#define PAD_GPIOB08_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_5 */
#define PAD_GPIOB09_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_6 */
#define PAD_GPIOB10_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_7 */
#define PAD_GPIOB11_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NAND_CLE_R */
#define PAD_GPIOB12_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NAND_ALE_R */
#define PAD_GPIOB13_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD0 */
#define PAD_GPIOB14_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_UP | PAD_STRENGTH_2)		/* Pin Use: NAND_RNB */
#define PAD_GPIOB15_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD1 */

#define PAD_GPIOB16_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NAND_NFOE_R_L */
#define PAD_GPIOB17_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD2 */
#define PAD_GPIOB18_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NAND_NFWE_R_L */
#define PAD_GPIOB19_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD3 */
#define PAD_GPIOB20_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD4 */
#define PAD_GPIOB21_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD5 */
#define PAD_GPIOB22_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD6 */
#define PAD_GPIOB23_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD7 */

#define PAD_GPIOB24_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CTP_RST_RTP_Y2_R */
#define PAD_GPIOB25_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CTP_INT_RTP_X2_R */
#define PAD_GPIOB26_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_HIGH | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: WIFI_PSW */
#define PAD_GPIOB27_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOB28_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOB29_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VOL_UP_L */
#define PAD_GPIOB30_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VOL_DOWN_L */
#define PAD_GPIOB31_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
/*------------------------------------------------------------------------------
*	GPIO Bank C
*/
#define PAD_GPIOC00_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC01_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC02_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC03_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC04_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PMIC_INT_L */
#define PAD_GPIOC05_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_UP | PAD_STRENGTH_2)		/* Pin Use: CIP_L */
#define PAD_GPIOC06_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: ACCEL_INT */
#define PAD_GPIOC07_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */

#define PAD_GPIOC08_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#if 1	/* 10feb14 Changed since C9, C10, C11, and C12 are just connected to test pads */
#define PAD_GPIOC09_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPCLK2 */
#define PAD_GPIOC10_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPFRM2 */
#define PAD_GPIOC11_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPRXD2 */
#define PAD_GPIOC12_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPTXD2 */
#else
#define PAD_GPIOC09_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPCLK2 */
#define PAD_GPIOC10_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPFRM2 */
#define PAD_GPIOC11_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPRXD2 */
#define PAD_GPIOC12_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPTXD2 */
#endif	/* 10feb14 */
#define PAD_GPIOC13_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC14_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC15_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_HIGH | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID2_ENA_L */

#define PAD_GPIOC16_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID2_RESET_L */
#define PAD_GPIOC17_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC18_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCLK2 */
#define PAD_GPIOC19_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCMD2 */
#define PAD_GPIOC20_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT20 */
#define PAD_GPIOC21_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT21 */
#define PAD_GPIOC22_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT22 */
#define PAD_GPIOC23_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT23 */

#define PAD_GPIOC24_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC25_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: nSWAIT */
#define PAD_GPIOC26_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC27_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC28_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC29_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPCLK0_R */
#define PAD_GPIOC30_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPFRM0 */
#define PAD_GPIOC31_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPTXD0 */
/*------------------------------------------------------------------------------
*	GPIO Bank D
*/
#define PAD_GPIOD00_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPRXD0 */
#define PAD_GPIOD01_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: MCU_PWM0 */
#define PAD_GPIOD02_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SCL0 */
#define PAD_GPIOD03_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDA0 */
#define PAD_GPIOD04_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SCL1 */
#define PAD_GPIOD05_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDA1 */
#define PAD_GPIOD06_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CTP_SCL_RTP_Y1_R */
#define PAD_GPIOD07_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CTP_SCL_RTP_X1_R */

#define PAD_GPIOD08_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOD09_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SDOUT */
#define PAD_GPIOD10_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SBCLK */
#define PAD_GPIOD11_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SDIN */
#define PAD_GPIOD12_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SSYNC */
#define PAD_GPIOD13_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SMCLK */
#define PAD_GPIOD14_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_UP | PAD_STRENGTH_2)		/* Pin Use: RX0 */
#define PAD_GPIOD15_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */

#define PAD_GPIOD16_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOD17_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOD18_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: TX0 */
#define PAD_GPIOD19_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_HIGH | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: WIFI_RST_L */
#define PAD_GPIOD20_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CHG_FLT */
#define PAD_GPIOD21_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOD22_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCLK1_R */
#define PAD_GPIOD23_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCMD1_R */

#define PAD_GPIOD24_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT10_R */
#define PAD_GPIOD25_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT11_R */
#define PAD_GPIOD26_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT12_R */
#define PAD_GPIOD27_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT13_R */
#define PAD_GPIOD28_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_0 */
#define PAD_GPIOD29_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_1 */
#define PAD_GPIOD30_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_2 */
#define PAD_GPIOD31_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_3 */
/*------------------------------------------------------------------------------
*	GPIO Bank E
*/
#define PAD_GPIOE00_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_4 */
#define PAD_GPIOE01_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_5 */
#define PAD_GPIOE02_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_6 */
#define PAD_GPIOE03_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_7 */
#define PAD_GPIOE04_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_PCLK */
#define PAD_GPIOE05_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_HIGH | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_ENAL */
#define PAD_GPIOE06_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_RESET_L */
#define PAD_GPIOE07_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */

#define PAD_GPIOE08_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOE09_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DPAD_LEFT_L */
#define PAD_GPIOE10_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: HP_DETECT */
#define PAD_GPIOE11_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CHG_INT */
#define PAD_GPIOE12_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOE13_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOE14_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_HIGH | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SCK_R */
#define PAD_GPIOE15_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_HIGH | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: LCD_SCS_L */

#define PAD_GPIOE16_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOE17_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOE18_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOE19_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_HIGH | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDI */
#define PAD_GPIOE20_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: HOME_BTN_L */
#define PAD_GPIOE21_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DPAD_DN_L */
#if 1	/* 8apr14: output high, so backlight will be on */
#define PAD_GPIOE22_CABO_ALPHA		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_HIGH | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: LCD_LED_ENA */
#else
#define PAD_GPIOE22_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: LCD_LED_ENA */
#endif	/* 8apr14 */
#define PAD_GPIOE23_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DPAD_RIGHT_L */

#define PAD_GPIOE24_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DPAD_UP_L */
#define PAD_GPIOE25_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TRST_L */
#define PAD_GPIOE26_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TMS */
#define PAD_GPIOE27_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TDI */
#define PAD_GPIOE28_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TCK */
#define PAD_GPIOE29_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TDO */
#define PAD_GPIOE30_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: USB_OTG_ID */
#define PAD_GPIOE31_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: USB_PWR_OK_L */
/*------------------------------------------------------------------------------
*	GPIO Bank ALV
*/
#define PAD_GPIOALV00_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOALV01_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOALV02_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOALV03_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOALV04_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOALV05_CABO_ALPHA		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */


/*------------------------------------------------------------------------------
*	BUS Signal
*/
#define	PAD_BUS_STATIC_CNTL_CABO_ALPHA	(NX_CLKPWR_BUSPAD_STATIC_CNTL | PAD_STRENGTH_2)
#define	PAD_BUS_STATIC_ADDR_CABO_ALPHA	(NX_CLKPWR_BUSPAD_STATIC_ADDR | PAD_STRENGTH_2)
#define	PAD_BUS_STATIC_DATA_CABO_ALPHA	(NX_CLKPWR_BUSPAD_STATIC_DATA | PAD_STRENGTH_2)
#define	PAD_BUS_HSYNC_CABO_ALPHA	(NX_CLKPWR_BUSPAD_HSYNC | PAD_STRENGTH_2)
#define	PAD_BUS_VSYNC_CABO_ALPHA	(NX_CLKPWR_BUSPAD_VSYNC | PAD_STRENGTH_2)
#define	PAD_BUS_DE_CABO_ALPHA	(NX_CLKPWR_BUSPAD_DE | PAD_STRENGTH_2)

extern const U32 io_pad_cabo_alpha[NUMBER_OF_GPIO_MODULE][32];

#ifndef ALVPADS
#define ALVPADS 6
#endif
extern const U32 alv_pad_cabo_alpha[ALVPADS];

extern const U32 bus_pad_cabo_alpha[6];
#endif /* __CFG_GPIO_CABO_ALPHA_H__ */
